- nwb_datajoint/data_import/insert_sessions.py
Fix #21.
My bad - I forgot about a change I made in HDMF to make the last set of changes work. Since it could be some time before a new version of HDMF is released, I use a simple workaround here to make sure that the new linkraw file contains a link to the raw data in the original file.
> Fix missing acquisition link in linkraw

- README.md
- franklab_kachery-p2p_config.yaml
- nwb_datajoint/common/common_spikesorting.py
- run_kachery_p2p_daemon.sh
Please feel free to take or drop any of these changes @khl02007 
- Added config file and script to run kachery_p2p daemon in the background. The config file is downloaded from Kyu's git gist (the url). I had to change the option from `--config` to `--static-config`. The bash script (with nohup and stout directing) is useful for me, but not sure if/where you want to keep it in this repository.
- Updated README with instructions to install spikeextractors and spiketoolkit packages locally. This should fix #29 .
- Fixed makedirs() behavior to prevent error when overwriting analysis path.
> fix prerequisites and overwrite behavior

- requirements-dev.txt
- src/nwb_datajoint/tests/conftest.py
- src/nwb_datajoint/tests/test_1.py
Prior to this PR, tests were not runnable for several reasons:
1. Error `Defining 'pytest_plugins' in a non-top-level conftest is no longer supported` (@khl02007 FYI)
2. Imports have changed
3. Data directories have changed
4. File path handling (str vs path) has changed
5. Package now assumes there is an `ElectricalSeries` named "e-series" in the file
6. possibly other reasons to be discovered.
So far, I have addressed issues 1-3 in this PR. Tests currently fail because of issues 4 and 5 (at least). I am sorting out issue 5 in a separate PR not yet pushed. 
Also, some tests may no longer be needed and should be removed if not needed. And some files have the word "test" in them (e.g. in `notebooks/`) which make them automatically run by `pytest`. It seems like these may have been one-off …
> Update test framework to more working state

- src/nwb_datajoint/common/nwb_helper_fn.py
- tests/test_nwb_helper_fn.py
When `get_electrode_indices` was passed an `ElectricalSeries` object, the electrode row indices were being matched against the given electrode IDs instead of the IDs. This PR fixes that issue.
This also adds tests to ensure the function works and demonstrate the intended behavior.
> Fix get_electrode_indices for given ElectricalSeries

- src/nwb_datajoint/common/common_task.py
- src/nwb_datajoint/common/nwb_helper_fn.py
This commit https://github.com/LorenFrankLab/nwb_datajoint/commit/e7574d41ce3ad46cbb294121fe2fc4766a3162c9 resolved #54. However, the `isinstance` check on `get_data_interface` is useful when different objects have a matching name but an incorrect type (especially considering across files from different labs). 
This PR reverts the above commit, adds documentation, and fixes how `get_data_interface` is called in `TaskEpoch` so that it is populated correctly.
> Revert usage of get_data_interface, fix TaskEpoch not populating

- tests/conftest.py
- tests/datajoint/_datajoint_server.py
Initialize the internal `__PROCESS` variable so that if a test fails, another error is not triggered because `__PROCESS` is not initialized.
Also delay for 15 seconds testing whether the datajoint server is fully up.
> Minor test improvements

- src/nwb_datajoint/common/populate_all_common.py
- src/nwb_datajoint/data_import/insert_sessions.py
`insert_sessions` which calls `copy_nwb_link_raw_ephys` will now create a copy of the NWB file and link not only the raw ephys data but also the analog sensor data which is currently large and not being used. This also speeds up the copying process.
For example, if the raw data is 88 GB, then before this change, the copied file would be 16 GB. Now it is 4 GB.
> Remove analog processing module from copied NWB file

- src/nwb_datajoint/common/common_ephys.py
- src/nwb_datajoint/common/common_spikesorting.py
- src/nwb_datajoint/common/common_task.py
This change excludes invalid times as indicated by the interval_list associated with a spike sorting recording, prior to spike sorting. This was an intended use of the interval_list per @lfrank.
> Exclude invalid times as indicated by interval_list prior to spike sorting

- src/nwb_datajoint/common/__init__.py
- src/nwb_datajoint/common/common_position.py
Imports into the top level of nwb_datajoint.common from common_position were circular, creating a foreign key reference error. This PR removes the circularity within the common_position module and therefore allows imports into the top level. All tests should be passing now.
> Fix position imports

- src/nwb_datajoint/common/common_filter.py
The code `raise Warning(...)` will raise an error that stops execution. This appears not to be the intended behavior. The correct code to show a warning is `warnings.warn(...)`.
I also made minor formatting changes to `common_filter.py` so that it is compliant with PEP8 code style.
> Fix formatting, show warning instead of raise error

- src/nwb_datajoint/common/common_spikesorting.py
> Move lab team to primary key for `SpikeSortingRecordingSelection`

- src/nwb_datajoint/common/common_interval.py
I ran into a problem in the case where the interval list was a single element. In that case the following returned a 1-d array rather than a 2-d array.
```
interval_list1 = reduce(_union_concat, interval_list1)
```
which caused a crash later on in the code. The solution was to add a test for `ndim==1` as in other parts of the code.
> include interval list check

- src/nwb_datajoint/common/common_nwbfile.py
- src/nwb_datajoint/data_import/insert_sessions.py
This should set the permissions on the _.nwb file and AnalysisNWBFiles to 644 to make sure that only the user can delete them. I have not yet tested this, however.
> use stat. codes for permissions

- docs/session_groups.md
- src/nwb_datajoint/common/__init__.py
- src/nwb_datajoint/common/common_session.py
With this PR I propose to create a SessionGroup table comprising groups of sessions.
This is a needed in the development of spyglassview (figurl view of spyglass sessions) to allow the user to choose exactly the collection of sessions they want to view (or share a view with others). This could also be helpful in eventually making a subset of the data available for readonly public access. I could also imagine this being useful for users who want to organize their studies.
Each session group has a name (primary key) and a description. See [session_groups.md](https://github.com/scratchrealm/nwb_datajoint/blob/session-groups/docs/session_groups.md) for the proposed usage.
@lfrank @rly @edeno @khl02007 @jsoules
> PROPOSAL: implement SessionGroup

- src/nwb_datajoint/common/common_spikesorting.py
This is just a band-aid for unblocking folks. See issue #150 (maybe #153 ?). This PR simply changes n_jobs = 1 instead of 4 to address some parallelization issues. For longer term solution, I propose exposing n_jobs and total_memory as parameters the user can define depending on their known compute resources (5GB probably doesn't make sense on a virga, for ex... maybe we should also bump this up to something like 100GB for now?). These params could either go in SpikeSortingPreprocessingParameters or another more appropriate place.
Based on my experience, just to keep track -
* n_jobs = 4, three epochs of run data from one day: is extremely slow (> 4 hours on this attempt so far), I expect it to error out but it hasn't yet... still running. Based on htop, doesn't look like much is going …
> Change n_jobs from 4 to 1 for saving new recordings

- src/nwb_datajoint/common/common_device.py
Old yamls had MCU in the system device field. This replaces that with SpikeGadgets to make the name more specific.
> If system device is MCU, replace with SpikeGadgets

- src/nwb_datajoint/spikesorting/spikesorting_sorting.py
Looks like only `_get_recording_name` was defined for SpikeSorting() - I don't see `_get_sorting_name` defined - so it seems like `_get_recording_name` should be called here? If someone prefers to rename the method that approach could work too I think.
> Use defined method name

- src/nwb_datajoint/spikesorting/spikesorting_sorting.py
Use `if len(artifact_times)` instead of just `if artifact_times` because truth value of an array with more than one element is ambiguous. The latter gave me an error about the ambiguity of "if artifact_times." Please check whether this is the intended boolean evaluation to use here, or whether another use such as .any() or .all() is what was intended. Thanks.
> Fix ambiguous truth value of an array

- src/nwb_datajoint/spikesorting/spikesorting_sorting.py
The dimension expansion (previous line 118) led to attempted artifact removal even when no artifacts exist, which gave an index error. By putting the dimension expansion after checking the length of artifact_times, this can be avoided.
> Do not run artifact removal code if no artifacts

- src/spyglass/spikesorting/spikesorting_curation.py
Currently, when populating CuratedSpikeSorting, the query of SortInterval returns multiple items when it is meant to return one, because the query is not specific enough (nwb file is not included). This results in an error. This pull request uses the full key (with nwb file) to query SortInterval. This change has been tested. Thanks @dpeg22 for help with debugging this.
> query SortInterval with full key when populating CuratedSpikeSorting

- examples/cli_examples/create_session_group.py
- examples/cli_examples/create_spyglass_view.sh
- examples/cli_examples/readme.md
- src/nwb_datajoint/cli/cli.py
- src/nwb_datajoint/common/common_session.py
Added a new command for creating a spyglassview figURL for a particular session group.
From command line:
```bash
spyglass create-spyglass-view <session_group_name>
```
or from Python
```python
from nwb_datajoint.common import SessionGroup
session_group_name = '...'
url = SessionGroup.create_spyglass_view(session_group_name)
print(url)
```
Here's an example spyglassview figURL: https://www.figurl.org/f?v=gs://figurl/spyglassview-1&d=1292f87b3fd4d77b4ed5569597c3f64dd07ddfb7&channel=flatiron1&label=spyglass%20view
For info on creating a session group: [session_groups.md](https://github.com/LorenFrankLab/nwb_datajoint/blob/master/docs/session_groups.md)
Also added `skip_duplicates` parameter in `SessionGroup.add_group()` and `SessionGroup.add_session_to_group()`
> implement create-spyglass-view

- src/spyglass/spikesorting/spikesorting_artifact.py
Previous version of `_get_artifact_times` expected `AppendSegmentRecording`, but a saved `AppendSegmentRecording` that is loaded (and passed as input) becomes a `BinaryRecordingExtractor` that no longer has `recording_list` property. Added some checks to take the appropriate concatenation step depending on recording type.
> Add check to concatenate recording depending on type

- src/spyglass/spikesorting/spikesorting_sorting.py
Cannot just use intersection of ArtifactRemovedIntervalList and key for retrieving the artifact intervals in case where the artifact interval was computed with a different sort interval; making it more specific
> Find correct artifact time

- src/spyglass/spikesorting/spikesorting_curation.py
If a recording has multiple (disjoint) sort intervals, it is saved as `AppendSegmentRecording` with each sort interval as a recording segment to preserve timestamps. But a sorting is always single-segment, because MS4 has to concatenate the recording segments before sorting (i.e. cannot sort multi-segment recordings). So there can be a mismatch in the number of segments. This PR concatenates the recording segments to a single segment before computing waveforms.
> Concatenate recording before computing waveforms

- src/spyglass/common/nwb_helper_fn.py
The position intervals typically have intervals. One extremely small interval and one that contains the rest of the data. According to @lfrank this is the result of trodes starting up. 
This PR increases the minimum valid length of position tracking to 1 second, which should prevent this extremely small interval from being included in the data.
> Set minimum valid length of position intervals to 1 second

- src/spyglass/spikesorting/spikesorting_artifact.py
- src/spyglass/spikesorting/spikesorting_sorting.py
Bug fix in `spikesorting_artifact.py`
In `spikesorting_sorting.py` added minimum possible pad to `ms_after` argument in call to `si.toolkit.remove_artifacts()` to ensure zeroing of artifact times. 
Tested `ArtifactDetection` using `artifact_params_name`s: 'test_amp_no_z', 'test_no_amp_z', 'test_no_amp_no_z', 'test_amp_z'.
Tested removal of artifacts using below (see .md for jupyter notebook):
```python
from pathlib import Path
import datajoint as dj
import os
os.environ['SPYGLASS_BASE_DIR'] = "/stelmo/nwb/"
os.environ['SPYGLASS_RECORDING_DIR'] = "/stelmo/nwb/recording"
os.environ['SPYGLASS_SORTING_DIR'] = "/stelmo/nwb/sorting"
os.environ['SPYGLASS_WAVEFORMS_DIR'] = "/stelmo/nwb/waveforms"
os.environ['SPYGLASS_TEMP_DIR'] = "/stelmo/nwb/tmp"
os.environ['KACHERY_DAEMON_HOST'] = "typhoon" …
```
> Artifact bug fix

- src/spyglass/common/common_nwbfile.py
See issue #252 . This change enables the user to set the name of the dynamic table when created from a dataframe before adding it as an nwb object to an analysis nwb file. Previously, the name was hard coded as 'pandas_table' which disallowed the entry of more than one dataframe into an analysis nwb file, because they would have the same name. Now, the user can set a name for each table so that multiple dataframes can be converted to hdmf dynamic tables and added as uniquely named nwb objects to an analysis nwb file. Tested locally. This change does not impact file reading as far as I understand, because nwb objects are fetched using the object id regardless of the nwb object type.
> Enable adding >1 dataframes to an analysis nwb

- src/spyglass/spikesorting/spikesorting_artifact.py
Variable `data` in `_get_artifact_times` is a spikeinterface recording with the `.get_traces()` method applied. This variable `data` has shape (timepoints, electrodes). Z-scoring with axis=1 is z-scoring across all electrodes at one timepoint. Instead, the z-scoring should be applied to axis=0 such that we z-score across all timepoints of one electrode.
This was identified by @emilymonroe95 who noticed that some z score threshold crossings should have been identified but weren't detected by the artifact detection algorithm. This change has been tested locally.
The axes can get a bit confusing so would greatly appreciate if someone can confirm that this is what you also think we want to do here. Thank you.
If helpful, see @emilymonroe95 initial exploration with a small example dataset …
> apply zscore across times, within electrode

- src/spyglass/spikesorting/sortingview.py
@dpeg22  and I (in reference to issue #269) found that the insert_manual_curation function was fetching a 'metrics' attribute where it should be named 'quality_metrics', as seen in the Curation table. I tested this change locally and it fetches the desired metrics, and adds the correct manual curation to the Curation table.
>  insert_manual_curation- fetch "quality_metrics" instead of "metrics"

- requirements-dev.txt
- src/spyglass/common/common_nwbfile.py
- src/spyglass/spikesorting/spikesorting_curation.py
This pull request aims to address #130 by calculating a `peak_channel` metric during population of the `QualityMetrics` table and to add this information to the `CuratedSpikeSorting.Unit` table. This metric returns the `electrode_id` (matches the `electrode_id` in the `Electrode`/`ElectrodeGroup`/`SortGroup.SortGroupElectrode` table) of the channel within the sort group that has the peak amplitude for that unit.
An edit to `common_nwbfile.py` is also included to allow adding labels to the units table that lives within an `AnalysisNwbfile`.
Most of the commits are code that has been copied from #249, which is now closed. I would appreciate any feedback.
> Add peak channel metric to Unit table

- environment.yml
This PR limits sortingview version to 0.7.4. The newer versions break our code because it is not backwards compatible. We will remove this once we make a switch to the new sortingview.
> Limit sortingview version

- config/dj_config.py
This pull request disables the checksum for large files (>1 GB). Large files can take a long time to checksum and slows down the ability to analyze files.
One thing I'm not sure about is if there are other places where this bit of code should be run. Right now this is only in dj.config, which people run when they are setting up an account. Other users will have to do this on their own.
Secondly, I'm unsure of the impact of this setting this variable if people do not have the latest version of datajoint (>13.6).
This PR is related to issue #275
> disable checksum for files > 1 GB

- src/spyglass/spikesorting/spikesorting_recording.py
Fix for issue #276. In brief, the current pipeline raises an error when trying to generate spikesorting recording files from recordings with small valid segments. This pull request allows a user to pass an optional parameter called 'min_segment_length' which is used to exclude intervals shorter than the value specified by the parameter.
With the proposed code, I was able to generate a spikesorting recording for a file with small segments that was previously giving an error. I also checked that the interval list of valid times stored after excluding small segments was as expected (contained no segments less than min_segment_length and contained all segments larger than min_segment_length).
> use min_segment_length when creating spikesorting recording

- src/spyglass/spikesorting/spikesorting_curation.py
I get an error that st has no attribute "whiten", and this change to using spikeinterface instead of its toolbox,(after consulting with @khl02007 earlier) fixed it.
> Use "si" instead of "st" to whiten waveforms

- src/spyglass/spikesorting/spikesorting_curation.py
Before, the code would error out when calculating peak offset using whitened waveforms. With testing, we see there are only small differences between the two (thus, we should keep the note for future users, but make it a warning instead of an exception).
> Exception->Warning concerning whitened peak-offset

- src/spyglass/common/common_nwbfile.py
Update to split up analysis files; tested to work for old files.
We currently have ~355k files in /stelmo/nwb/analysis and Dirk strongly suggested that we split them among subdirectories. I don't know how to move the current files (although I've asked DataJoint if there is a way to do this) and this pull request creates one subdirectory per main nwb file for new AnalysisNwbfiles
> Analysis_file_path

- src/spyglass/spikesorting/spikesorting_sorting.py
Minor change to be consistent with the latest spikeinterface, which now has the option of removing single samples by setting `ms_before` and `ms_after` to `None`
> Change remove artifact

- README.md
- pyproject.toml
Even though the person who previously had the spyglass name removed it from pypi, the rules for taking over that namespace are rather strict and cumbersome for security reasons. See [PEP-541](https://peps.python.org/pep-0541/#how-to-request-a-name-transfer)
I have changed the package name to `spyglass-neuro` for pip and conda and added the instructions. @khl02007 and I have tested the installs under this name and importing spyglass still works.
> Need to use `spyglass-neuro` for package name

- src/spyglass/spikesorting/spikesorting_curation.py
The fraction of the ISIs that are violations is the number of ISIs that are violations over the number of ISIs. Previously, the number of ISI violations was divided by the number of spikes to calculate this quantity. This pull request replaces the number of spikes with the number of ISIs.
> Calculate fraction of ISIs that are violations

- src/spyglass/common/common_filter.py
This PR addresses iss #359, which, in short, identified a bug in `common_ephys.FirFilter` where `filter_type` was not properly inserted into the table. This PR adds `filter_type` as an entry to the `filterdict` dictionary, which is eventually inserted into the FirFilter table on line 119. This was tested once (see `FirFilter` entry LFP 300-600 Hz with `filter_type` 'bandpass').
> Address issue #359 add filter_type to filterdict

- src/spyglass/common/common_ripple.py
This adds a new module in the `common` package called `common_ripple`. It allows the user to select an epoch and a set of electrodes to do ripple detection. I have enabled the ability to do ripple detection for different brain regions using the `brain_region` key.
> Add ripple detection tables

- src/spyglass/common/common_behav.py
Currently, we get the path to the video file associated with an nwb file and epoch using the external_file field of the video object in the NWB file. This breaks when a user moves a video file from it's original location when the NWB file was created. This method on the `VideoFile` table uses the `SPYGLASS_BASE_DIR` environment variable and the name of the video file, as listed in the NWB file, to look for the video file in a video folder (in our case `/stelmo/nwb/video/`). It returns a FIleNotFound error if the video file is not in the directory specified by `SPYGLASS_BASE_DIR/video`. 
Open to any feedback others may have. @acomrie may have further rationale for why this is necessary.
> Add method to VideoFile to return absolute path based on environment variable

- config/dj_config.py
In dj_config.py, the second argument should be the datajoint_config.yml file, but that doesn't get passed through.
This is a one-line modification to fix that.
> dj_config handle second argument (one-line fix)

- environment.yml
the most recent versions of pyfftw and ghostipy don't work. during LFP filtering they give an error about no specifying the number of threads. maybe this can be used in the future to parallelize lfp filtering.
> pyfftw and ghostipy versions

- environment.yml
- franklab_scripts/nightly_cleanup.py
- franklab_scripts/sort.py
- pyproject.toml
- src/spyglass/cli/cli.py
- src/spyglass/common/common_position.py
- src/spyglass/common/common_session.py
- src/spyglass/common/nwb_helper_fn.py
- src/spyglass/decoding/clusterless.py
- src/spyglass/decoding/core.py
- src/spyglass/decoding/sorted_spikes.py
- src/spyglass/decoding/visualization.py
- src/spyglass/decoding/visualization_1D_view.py
- src/spyglass/decoding/visualization_2D_view.py
- src/spyglass/spikesorting/merged_sorting_extractor.py
- src/spyglass/spikesorting/sortingview_helper_fn.py
- Black updated to a new stable version causing our linting checks to fail. This fixes the linting.
- There were invalid restrictions in the pyproject.toml on version numbers. Thanks to @dpeg22 for pointing out which ones. I removed the restrictions on the two offending dependencies: pydotplus, pymysql
- I also removed the restrictions on pip and dask. Both because I didn't see the reason for them. Hopefully will not fail in the future.
> Fix formatting and dependencies

- src/spyglass/position/__init__.py
- src/spyglass/position/position_dlc_selection.py
- src/spyglass/position/position_position.py
- src/spyglass/position/position_trodes_position.py
This is an option for modifying the table names in order to reduce confusion.
Addresses: https://github.com/LorenFrankLab/spyglass/pull/367#discussion_r1105259668
It changes
```python
position.IntervalPositionInfoSelection -> position.PositionOutputSelection
position.IntervalPositionInfo -> position.PositionOutput
position.PosSource -> position.PosMerge
```
It also adds an import for IntervalPositionInfo from the common_position schema
```python
from ..common.common_position import IntervalPositionInfo as CommonIntervalPositionInfo
```
> Rename final position tables and add common_position to PosMerge table

- src/spyglass/common/common_ripple.py
Fixes #406 This pull request changes the dependency structure of the ripple detection tables to allow for ripple detection to operate on a specific interval list name and within the subset of electrodes used during ripple band LFP extraction.
> [WIP] Change ripple tables to allow for increased specificity of ripple detection intervals and electrodes

- src/spyglass/common/common_device.py
Update on #430. Based on discussion on Slack, @khl02007 and I think it would be best not to auto-capitalize every amplifier and adc_circuit. This changes the code so that "intan" vs "Intan" is handled specially given that Frank Lab NWB files have both.
> Handle Intan capitalization specially

- src/spyglass/spikesorting/spikesorting_curation.py
Change lab default metric params to reflect changes to spike interface functions. Addresses #445 and #442.
> update default metric params

- src/spyglass/spikesorting/spikesorting_sorting.py
@jguides 
This is in response to recent changes in spikeinterface that breaks whitening by mountainsort4 (due to preserving recording dtype). It is recommended to use MS4 params where `whiten=False`
> Add whitening prior to sorting

- src/spyglass/common/common_dio.py
This is a plot that helps someone view all their DIO ticks in a given session in order to check their data. Here is an example:
```python
(DIOEvents() & {'nwb_file_name': "arthur20220314_.nwb"}).plot_all_dio_events()
```
> Add plot to plot all DIO events in a session

- environment.yml
- pyproject.toml
- src/spyglass/common/common_position.py
Numba can't handle the latest version of numpy (numpy version 1.24, see https://github.com/numba/numba/issues/8615) 
This fixes issue #461. Also may fix @MichaelCoulter's issue #455.
> Temporarily pin numpy < 1.24 to fix numba issues

- src/spyglass/common/common_interval.py
- src/spyglass/spikesorting/spikesorting_artifact.py
- tests/common/test_common_interval.py
Previously `artifact_removed_valid_times` was the same as `artifact_times` because the code was taking the intersection between the timestamps and `artifact_times` instead of set-theoretic difference. This PR fixes that.
> Fix artifact removed valid times

- src/spyglass/common/common_filter.py
Quick fix of 30 khz lfp filter description typo to say 30 khz instead of 20 khz.
Note if downstream things are using this table entry already then we might consider a manual update to the current entry within our existing FirFilter table rather than deleting and recreating standard filters.
> Fix common_filter.py little typo

- src/spyglass/lfp/v1/lfp.py
I think we'd like to `skip_duplicates` when inserting lfp electrode groups rather that error out upon inserting duplicates. Open to alternative approaches too.
> Update lfp.py for usability

- environment_position.yml
- src/spyglass/position/v1/position_dlc_centroid.py
This PR adds PyBind11 to the list of packages installed by conda during spyglass-position environment creation. There was an error being thrown do to pybind11 not being found during isosplit5 build. This fix seems to prevent that error and allow for a clean install. It also updates the version of sortingview required to match the current spyglass environment requirements.
It also catches two cases during centroid determination in position_dlc_centroid.py where an `if` was used with no `else`.
> Make fixes to spyglass-position env creation and catch centroid cases

- notebooks/02_curation.ipynb
- notebooks/03_lfp.ipynb
- src/spyglass/common/__init__.py
- src/spyglass/common/common_ephys.py
- src/spyglass/common/common_filter.py
- src/spyglass/lfp/v1/lfp.py
See discussion in https://github.com/LorenFrankLab/spyglass/issues/488
I have renamed the FirFilter table to FirFilterParameters in the MySQL database a few minutes ago. This PR updates the spyglass code to use the new table name. Running the old code may create a new FirFilter table (old name), but it should not get populated. I will keep an eye on the database to see if one gets created and drop the table to avoid future confusion.
> Rename FirFilter to FirFilterParameters

- CHANGELOG.md
- CITATION.cff
- pyproject.toml
The breaking change to the name of the `FirFilter` table in #512 means that users using an older version of spyglass will be accessing a newer, partially incompatible version of the production database. To help users using pip-installed older versions of spyglass update, we should release a new version of spyglass.
> Update version and changelog for 0.4.0 release

- src/spyglass/position/position_merge.py
This pull request adds a fetch_nwb method to PositionOutput. This allows a user to call fetch_nwb on the merge table and return the NWB objects from the associated part table.
> Add fetch_nwb method to PositionOutput

- .git_archival.txt
- .gitattributes
- .github/workflows/test-conda.yml
- .github/workflows/test-package-build.yml
- .gitignore
- pyproject.toml
- setup.py
- src/spyglass/__init__.py
This PR allows us to use dynamic versioning that relies on git tags (for example, we claim to be on version 4.0 but we have not made a tagged release for it).
It also eliminates the use of setuptools and setup.py which the python community is moving away from.
See: https://effigies.gitlab.io/posts/python-packaging-2023/
> Use hatch, eliminate setup.py, use dynamic versioning

- docs/src/misc/merge_tables.md
- src/spyglass/common/common_ephys.py
- src/spyglass/lfp/lfp_merge.py
- src/spyglass/lfp/v1/lfp.py
- src/spyglass/utils/dj_helper_fn.py
- src/spyglass/utils/dj_merge_tables.py
In this PR, I add a `Merge` class. This inherits from `dj.manual` and provides a series of methods for interacting with merge tables that adhere to a spec described in new documentation. This is not a new table type in the datajoint ontology, but a series of helper functions to support issues described [here](https://github.com/datajoint/datajoint-python/issues/151) and [here](https://github.com/LorenFrankLab/spyglass/issues/469). The only overwritten function is `insert` which supplies information in the master table. Others are prefixed with `merge_` to distinguish their use case. 
Additional minor changes...
- Rearrange tables in `lfp/v1/lfp.py` to ensure items are listed before foreign key references
- `common/common_ephys.py` adding warning specificity to notify an entry is skipped …
> Merge table class 

- src/spyglass/spikesorting/spikesorting_curation.py
- src/spyglass/spikesorting/spikesorting_sorting.py
Similar to #465 this PR addresses #559 by changing the dtype passed to `sip.whiten` 
The bug #559 describes is handled here by changing `np.float32` to `"float32"` in `spikesorting_sorting.SpikeSorting`.
The bug #555 describes and #465 handles exists in `spikesorting_curation.Waveform` and is fixed here by changing `np.float16` to `"float32"` to reflect #559.
> Change to recording whitenening dtype

- src/spyglass/common/common_behav.py
- src/spyglass/common/common_task.py
This pull request will allow users to use Spyglass with recordings that made use of >1 camera within a single epoch. Two main changes need to be made to the 1) `TaskEpoch` and 2) `VideoFile` tables.
1. My plan is to use `alter` to add a `camera_names` secondary key to `TaskEpoch`, which would be a list where each element is a dictionary of form `{"camera_name": camera_name}` and corresponds to a single entry in the `CameraDevice` table.
This would mean the nullable dependence on `CameraDevice` would be taken advantage of and all future entries would not be strictly dependent on `CameraDevice`.
2. For `VideoFile` I will again use `alter` to add `CameraDevice` as a nullable foreign key. In this case, `video_file_num` will only increment if there are multiple videos for an individual camera. …
> Allow for multiple camera recordings within single epoch

- environment.yml
- environment_position.yml
- pyproject.toml
In order to enable type hints with more modern syntax and also because earlier python version are being deprecated by other libraries.
> Bump python version required

- environment.yml
- environment_position.yml
Fix #596. I also currently cannot install a clean spyglass environment on my Mac M1 for the same reason. 
As I understand it, [nb_conda](https://github.com/Anaconda-Platform/nb_conda) is a jupyter extension that adds components to the jupyter interface that allow you to list the available conda environments, list packages in the current environment, and modify the environment. This package has not been updated in three years and appears to be incompatible with recent updates to jupyter or jupyter lab. Since this package seems to be auxiliary to the function of spyglass, I recommend that we remove it from the environment files to fix the current installation issues.
> Remove nb_conda from conda environment files to fix installation error

- src/spyglass/lfp/__init__.py
- src/spyglass/lfp/lfp_electrode.py
- src/spyglass/lfp/lfp_imported.py
- src/spyglass/lfp/lfp_merge.py
- src/spyglass/lfp/v1/__init__.py
- src/spyglass/lfp/v1/lfp.py
- src/spyglass/lfp_band/lfp_band_merge.py
This pull request moves `LFPElectrodeGroup` from `spyglass/lfp/v1/lfp.py` to `spyglass/lfp/lfp_electrode.py` and also changes the schema under which the table lives from `lfp_v1` to `lfp_electrode`. This will allow for use of the table by all LFP pipelines (except for `common_ephys.LFP`).
> Move LFPElectrodeGroup to lfp_electrode.py

- examples/db_alter.ipynb
Add a notebook to the `examples` directory that demonstrates my steps for altering a spyglass/datajoint database table used in #594. It also has some code with notes on the changes from #400. The process is very manual in order to double and triple check the changes in a local copy of the production database before applying them to the live production database. This notebook is not meant to be run "off-the-shelf" but used as a guide for how to implement any future table changes. 
Each situation is different. Renaming/moving a table is easy. Deleting empty tables that no other table references is easy. Moving data from one table to another is more difficult. Adding or removing primary keys on a table that many tables depend on is very difficult.
Regardless of the difficulty, be very …
> Add notebook demonstrating some approaches to alter tables manually

- src/spyglass/common/__init__.py
- src/spyglass/common/common_behav.py
- src/spyglass/decoding/clusterless.py
- src/spyglass/decoding/core.py
- src/spyglass/decoding/sorted_spikes.py
- src/spyglass/position/v1/position_dlc_pose_estimation.py
- src/spyglass/position/v1/position_dlc_selection.py
Addresses issue of position interval not always being "pos {epoch-1} valid times". 
- Introduces a new table `PositionIntervalMap` in `common_behav`  composed of `IntervalList` primary keys and `position_interval_name` secondary key
- Updates the `convert_epoch_interval_name_to_position_interval_name` function from the decoding core to make use of this table and moves it to `common_behav`. Function populates `PositionIntervalMap`  if map is not found, meaning shouldn't need to populate table elsewhere if you use this function.
-  `convert_epoch_interval_name_to_position_interval_name`  can find position interval using `nwb_file_name` and either `epoch` or `interval_list_name'
- Cleanup cases where position interval defined assuming epoch-1 with calls to this function
> Create Table and helper functions to get position interval name from Interval list key and/or epoch

- src/spyglass/ripple/v1/ripple.py
there was a problem with the position interval was shorter than the lfp_band interval when trying to detect ripples. i addressed this by restricting the valid times to the intersect between the lfp interval and the position interval.
> fix position interval issue in ripple detection

- src/spyglass/common/common_behav.py
- src/spyglass/position/v1/position_dlc_pose_estimation.py
- src/spyglass/position/v1/position_dlc_selection.py
Addresses issue #626 
- Populates PositionIntervalMap table during spyglass insertion
- Prevents attempts to populate PositionIntervalMap within DLC populate functions. Raises error if key is missing from PositionIntervalMap instead
- Populated PositionIntervalMap for existing sessions (locally, not in codebase)
> Fix interval map dj error

- src/spyglass/spikesorting/spikesorting_sorting.py
`spikeinterface` changed the name of the parameter. I am using version `0.98.2`.
> Fix parameter name for clusterless

- notebooks/11_2D_Clusterless_Decoding.ipynb
- src/spyglass/decoding/visualization.py
- src/spyglass/decoding/visualization_2D_view.py
Partially addresses `figurl-franklab-views` repo issue #19 (https://github.com/magland/figurl-franklab-views/issues/19) which requested that the 1D and 2D decode visualizations should be explicitly passed the track geometry, rather than inferring it from the animal position data.
This PR addresses the issue for the 2D case by removing the `make_track` code from `visualization_2D_view.py` (which was largely cut-and-paste from https://github.com/Eden-Kramer-Lab/replay_trajectory_classification/blob/master/replay_trajectory_classification/environments.py anyway) and instead requiring the physical track description to be input as two arrays:
- an array of `track_bin_centers`: `n_track_bins` x `2` where each outer entry has the `[x, y]` position (in native units) of the corresponding track …
> Support explicit 2d track definition.

- src/spyglass/spikesorting/__init__.py
- src/spyglass/spikesorting/spikesorting_populator.py
- isort to rearrange imports
- replace populate commands projected keys with restriction
- declare variables for dicts that get used mult times
- use list comprehension to add field to dicts when fetched
- above allows use of insert instead of insert1
- replace if len(x) > 0 checks with if x
- wrap comments and docstrings to len 80
- use string template for github url to avoid repeated declaration of str
- break long func into mult to avoid complexity and permit piecewise execution
- lookup selection table for defaults to separate out pipeline_params fetch
- defaults are not intuitive - rename in main pipeline?
> Spikesort populator efficiency improvements

- config/add_dj_collaborator.py
- config/add_dj_guest.py
- config/add_dj_module.py
- config/add_dj_user.py
Update config files to work with mysql 8
> Fix config for mysql 8

- src/spyglass/common/common_behav.py
Increase threshold for offset between intervals when mapping epochs to position to avoid missing dues to start timing of position and ephys data in experiment
> Increase tolerance for interval allignment

- src/spyglass/common/common_interval.py
- src/spyglass/common/common_region.py
- src/spyglass/spikesorting/spikesorting_artifact.py
When using settings for Artifact detection is None in the spikesorting pipeline,  the recording interval is created with the incorrect shape (e.g. (2,) instead of (1,2)). 
This PR changes the shape created in line 200 of `spikesorting_artifact.py` (ArtifactDetection is None case) to match that in line 256 of `spikesorting_artifact.py`  (ArtifactDetection occurs case)
> Spikesorting artifact interval debug

- src/spyglass/common/common_position.py
- Enable correctly populating TrodesPos when columns in position dataframe contain correct xloc yloc elements but in a different order or with additional column values. Necessary for data from older rec_to_nwb conversions 
- Fix minor bug arising from checking if frame indexes are present
> Fix Minor bugs in TrodesV1 pipeline

- .github/workflows/test-package-build.yml
- .vscode/settings.json
This PR updates the release action to use trusted publishing instead of github secrets.  From this [blog post](https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/): 
> This method can be used in automated environments and eliminates the need to use username/password combinations or manually generated API tokens to authenticate with PyPI when publishing.
This is recommended by PyPI.
I also added isort on save for vscode settings.
> Use trusted publishing for releases

- src/spyglass/common/common_position.py
Fixes #679.  Adds an error and suggested fix in cases where LED separation is too high in every frame. Note that this case would cause a later less-informative error prior to this PR, so doesn't remove any functionality.
> Add error message for single-led with wrong parameters

- src/spyglass/common/common_position.py
- src/spyglass/settings.py
Fixes several issues in the `positionVideo` make function
- Minor changes to make the raw_dir string and access to the video file path in the nwbfile work correctly
- Allow table to make videos with position data upsampled for decoding
- Ensures proper selection of position data from the nwbfile spatial series across more versions of rec_to_nwb/trodes_to_nwb conversion. (now matches strategy in TrodesPosV1 pipeline from 59b68df)
- Use the video_dir to access the video file
- [ na] I have added/edited docs/notebooks to reflect the changes
> positionVideo debug

- notebooks/04_PopulateConfigFile.ipynb
Fix #648.
@khl02007 @edeno As I was writing this tutorial, I realized that there is a lot of text and not much runnable code to go into this tutorial. We already have this page in the docs https://lorenfranklab.github.io/spyglass/latest/misc/insert_data/ . I based the tutorial in this PR on that text and I think I improved upon it. Should this tutorial replace that documentation page? Should we have both? What would you like to see in this tutorial that I am missing?
Aside: I used `Lab` as an example where this might be useful (current entries are: `{"Frank Lab", "Giocomo", "Loren Frank", "Loren Frank Lab"} but I forgot that we did not implement the ability to customize `Lab` using a config YAML. I'll add that functionality in a separate PR.
> [WIP] Add tutorial on customizing insert

- src/spyglass/spikesorting/spikesorting_artifact.py
In artifact detection, intervals with artifacts were being saved as a list of tuples rather than a 2D array, which is inconsistent with the `valid_times` in the  `IntervalList` table. This PR changes to make consistent.
> Make artifact interval a 2d array

- src/spyglass/common/common_nwbfile.py
Import library for Path which is needed for li 310 `base_dir = Path(os.getenv("SPYGLASS_BASE_DIR", None))`
> added Path library to imports

- CHANGELOG.md
- src/spyglass/common/common_filter.py
- src/spyglass/lfp/analysis/v1/lfp_band.py
Fixes minor bugs in the LFPBand population processs
- When making filtering intervals in `FirFilterParameters.filter_data()` skip zero-sized intervals which cause error in `ghostipy`
- When validating that a interval list created in `LFPBandV1.make()` matches a pre-existing ine with the same sampling rate, first apply `interval_list_censor()`. This is already applied when makeing the interval with a given sampling rate, and ensures that they will match if appropriate.
> Lfp band fixes

- src/spyglass/lfp/v1/lfp.py
Currently `LFPSelection` and `LFPV1` downsample the LFP from `Raw` to 1000 Hz, which is hard-coded. This change is intended to allow the user to downsample the LFP to a user-specified sampling frequency, which is needed because some analyses need to analyze higher frequencies than 500 Hz. 
-lfp.py: 1. Added `lfp_sampling_rate` as a secondary key which is the user-defined desired output sampling frequency. 
2. Changed `DECIMATION FACTOR` so that the resultant `decimation` input into `filter_data_nwb` will yield a sampling frequency equal to the user-desired desired output sampling frequency in `key["lfp_sampling_rate"]`. 
Note that this pull request entails adding a secondary key to an existing table. I was unable to test this pull request as I couldn't get permission for docker and …
> Make sampling rate for LFP user-defined instead of hard-coded to 1000 Hz

- CHANGELOG.md
- src/spyglass/utils/dj_merge_tables.py
I'm working on a solution for #226 and was coincidentally working on edits that fix #700 when @samuelbray32 reported the issue.
- Fixes #700 : Uses arg restriction on parent table, joins with merge-part to ID keys for deletion
- `spyglass/utils/dj_merge_tables.py`: only edits required for #700
> Delete downstream restriction fix 

- src/spyglass/spikesorting/spikesorting_sorting.py
Fixes #707 
Passes `remove_existing_folder=True` to spikinterface's `run_sorter()` in spikesorting v0 pipeline.  Needed to account for change of default value of this argument in spikeinterface.
> add remove_existing_folder argument

- src/spyglass/spikesorting/v1/recording.py
Appending the ref channel id to the list of channels in sort group fails because it used the wrong syntax. This fixes it.
- Fixes #000: How this PR fixes the issue
- `path/file.py`: Description of the change
- `path/file.py`: Description of the change
- Fixes #000: How this PR fixes the issue
- `path/file.py`: Description of the change
- `path/file.py`: Description of the change
> Fix ref channel append error

- src/spyglass/common/common_nwbfile.py
Fixes #712 
- Changes the method of defining file path in `AnalysisNwbFile.get_abs_path()` from using `SPYGLASS_BASE_DIR + "/analysis"` to `dj.config["stores"]["analysis"]["location"]`
- This ensures consistency with `AnalysisNwbFile.fetch("analysis_file_abs_path")` which is a datajoint filepath object.
- Enables users to set their analysis directory separate from the spyglass base directory if desired
- No changes to current users on Franklab network
> Change method of defining base dir in get_abs_path

- src/spyglass/lfp/lfp_merge.py
- src/spyglass/position/position_merge.py
- src/spyglass/position_linearization/position_linearization_merge.py
- Order of `SpyglassMixin` and `Merge` parent classes in Merge table definitions (e.g. `LFPOutput`) put priority on `SpyglassMixin` for functions defined in both
- Problem because merge tables need to use this function as defined in the `Merge` class.
- This PR switches the order of the two parent classes so this happens
> Priority for fetch_nwb function in merge tables

- .vscode/settings.json
- src/spyglass/spikesorting/merge.py
- src/spyglass/spikesorting/v1/recording.py
- src/spyglass/spikesorting/v1/sorting.py
This is a minor fix to handle single intervals in spike sorting
Also adds spyglass mixin to SpikeSortingOutput merge table
> Handle single intervals in spike sorting

- CHANGELOG.md
- notebooks/24_Linearization.ipynb
- notebooks/py_scripts/24_Linearization.py
- src/spyglass/common/common_position.py
- src/spyglass/lfp/lfp_merge.py
- src/spyglass/linearization/__init__.py
- src/spyglass/linearization/merge.py
- src/spyglass/linearization/v0/__init__.py
- src/spyglass/linearization/v0/main.py
- src/spyglass/linearization/v1/__init__.py
- src/spyglass/linearization/v1/main.py
- src/spyglass/position_linearization/__init__.py
- src/spyglass/position_linearization/v1/__init__.py
- src/spyglass/spikesorting/v1/sorting.py
- src/spyglass/utils/__init__.py
- src/spyglass/utils/dj_helper_fn.py
- src/spyglass/utils/dj_merge_tables.py
PR #694 had a lot of conflicts related to PR #711, and discussions suggested avoiding rename of existing tables. Rather than cherry pick and rebase, this PR replaces the work in #694.
The goal of this PR is demonstrated in the following image, where an import from the old location results in a warning, but an import from the new location does not:
- Revises changelog to separate change types
- Renames subpackage `position_linearization` -> `linearization` for more distinct prefix when navigating package
- Migrates tables
- `utils/dj_helper_fn.py`: Add deprecation factory, class that returns classes with an added `print` statement in the `__init__` that specifies where a table was migrated from/to
- `common/common_position.py` -> `linearization/v0/main.py`: Move 4 tables and replace with …
> V0 migration model, revised

- src/spyglass/common/common_session.py
Print statements were converted to using the logging module. Empty print statements do not error but logger.info does. This removes the leftover print statements.
> Remove logger.info() without message

- src/spyglass/position/position_merge.py
Fixes #745 
In `PositionOutput.fetch1_dataframe()`, there was a bug where the key was not projected to a datajoint query, causing an SQL error.  This fixes so that the key is a query.
> Fix PositionOutput.fetch1_dataframe bug

- src/spyglass/decoding/v1/clusterless.py
- src/spyglass/decoding/v1/sorted_spikes.py
Fixes #756 
- `get_position_info` in the v1 clusterless and sorted spikes decoding tables now restricts `PositionGroup` by "nwb_file_name" To avoid error when multiple groups from different sessions have the same "position_group_name"
> restrict get position info by session name

- src/spyglass/spikesorting/__init__.py
- src/spyglass/spikesorting/imported.py
- src/spyglass/spikesorting/v1/__init__.py
- Previously it was too short and threw an error upon insert.
- Also added `ImportedSpikeSorting` to the init of v1 and v0 so it can be called directly regardless of what version user imports.
- I have tested the changes by importing `spyglass.spikesorting.v1`
> Fix the length of `object_id` for `ImportedSpikeSorting`

- CHANGELOG.md
- src/spyglass/common/common_lab.py
- src/spyglass/lfp/v1/lfp.py
- src/spyglass/utils/dj_mixin.py
- @MichaelCoulter requested a printout of session/experimenters in the queue for deletion. This modifies the cautious delete function to generate that summary, and uses it to determine session experimenter missingness. The cautious delete function is now a bit slow as a result.
- `utils/dj_mixin.py`: Generate summary with `dj.U`, additional refinements to exploring graph for link to session table via primary key to permit the join, rather than finding session explicitly
- `common/common_lab.py`: add space after var in f-string
- Fixes: LFP pipeline was checking key for `target_sample_rate`, which wasn't present, as this is a secondary attrib. Discovered during #743, added here.
- `lfp/v1/lfp.py`: Add fetch statement, force decimation value as integer b/c later used in slicing
> Print session/exp summary, fix lfp target sample fetch

- src/spyglass/utils/nwb_helper_fn.py
Currently `RawPosition` is populated by loading spatial series with `get_all_spatial_series`, which calls `get_data_interface(nwbfile, 'position', pynwb.behavior.Position)`, which looks for an object of name `position` and type `pynwb.behavior.Position` within the processing modules of the NWB file. Some NWB files (e.g. the Buzsaki lab data) don't use the name `position` (instead they use `SubjectPosition`). As a result, the spatial series in the NWB file don't show up in `RawPosition` upon ingestion into spygass.
This fixes this by creating a new function called `get_position_obj` which looks for object of the type `pynwb.behavior.Position` within the `behavior` processing module of the NWB file without caring about the name. `get_all_spatial_series` now calls this function instead of …
> Add new function to retrieve spatial series from NWB file

- .pre-commit-config.yaml
- config/dj_config.py
- src/spyglass/common/common_behav.py
- src/spyglass/common/common_device.py
- src/spyglass/common/common_filter.py
- src/spyglass/common/common_interval.py
- src/spyglass/common/common_lab.py
- src/spyglass/decoding/v0/clusterless.py
- src/spyglass/decoding/v0/dj_decoder_conversion.py
- src/spyglass/decoding/v0/sorted_spikes.py
- src/spyglass/decoding/v0/visualization_2D_view.py
- src/spyglass/decoding/v1/clusterless.py
- src/spyglass/decoding/v1/dj_decoder_conversion.py
- src/spyglass/decoding/v1/sorted_spikes.py
- src/spyglass/position/v1/position_dlc_orient.py
- src/spyglass/position/v1/position_dlc_pose_estimation.py
- src/spyglass/position/v1/position_dlc_position.py
- src/spyglass/sharing/sharing_kachery.py
- src/spyglass/spikesorting/figurl_views/prepare_spikesortingview_data.py
- src/spyglass/spikesorting/v1/recording.py
- src/spyglass/utils/dj_helper_fn.py
- src/spyglass/utils/dj_merge_tables.py
- src/spyglass/utils/dj_mixin.py
- src/spyglass/utils/logging.py
- src/spyglass/utils/nwb_helper_fn.py
Single change to improve readability for #806, #807
> Blackify 24.1.1

- CHANGELOG.md
- src/spyglass/utils/dj_chains.py
- src/spyglass/utils/dj_mixin.py
- Fixes #820: Chains were attempting to apply downstream restriction to parent table. Add option to reverse chain order before applying restriction
- `dj_chains.py`: Accept arg to reverse join order
- `dj_mixin.py`: Add new arg to `_get_ext_summary` method
- Fixes #818: Adds join to prevent truncation from applying to restriction list. Adds fetch of QueryExpression to permit storage in table.
> Cautious delete bugfixes

- CHANGELOG.md
- src/spyglass/common/common_behav.py
- src/spyglass/common/common_usage.py
- src/spyglass/common/populate_all_common.py
- src/spyglass/linearization/__init__.py
- src/spyglass/utils/dj_merge_tables.py
- src/spyglass/utils/dj_mixin.py
Adds fault-permit insert process and a new table to common_usage to  keep track of errors across sessions. Will help monitor for recurring issues.
- Fixes #719: Adds try/catch to `populate_all_common`. For each fail, adds entry to `InsertError` table and returns the IDs of entries to the user.
- `common/populate_all_common.py`: Turn tables into a list to loop through, avoiding repeated logger calls. 
- `common/common_behav.py`: Adds a `populate` method to handle the fact that `PositionSource` was the only table in the previous list without a populate method. If unwanted, this change could instead be migrated to `populate_all_common` which would loop through a set of tables and methods to be run for each.
- This does not fully solve #804 because we expect the same fail state for the same …
> Fault-permit insert and remove mutual exclusivity protections on Merge

- src/spyglass/spikesorting/analysis/v1/group.py
Small bug fix in `SortedSpikesGroup.filter_units()`
- if `include_labels` is non-empty, unit labels must have at least one label from this list to pass filtering
- PR fixes a bug where all units were filtered out in empty `include_labels` case
> Only apply include labels filter if include_labels not empty

- CHANGELOG.md
- config/add_dj_collaborator.py
- config/add_dj_guest.py
- docs/src/misc/database_management.md
- src/spyglass/decoding/v1/sorted_spikes.py
- src/spyglass/spikesorting/analysis/v1/group.py
- src/spyglass/utils/database_settings.py
- src/spyglass/utils/dj_mixin.py
This PR makes edits to `database_settings.py` to allow for easier management of user permissions via roles. This would allow new modules to be added to the `dj_user` role, rather than require retroactive granting of access to the new module to all existing users by hand.
This PR also makes an edit to the PK of a params table in `decoding` that caused excessive key length errors.
> Proposed structure for user roles.

- src/spyglass/spikesorting/v0/spikesorting_populator.py
Minor bug.  Fixes what key is inserted in `CuratedSpikeSorting` when no curation done on the sorting results (as is the case in clusterless sorting
> fix CuratedSpikeSorting insert with no curation

- CHANGELOG.md
- src/spyglass/spikesorting/v0/spikesorting_artifact.py
- src/spyglass/spikesorting/v1/artifact.py
Fixes #858
- Error in edge case of single artifact interval
- In this scenario, the steps making artifact intervals disjoint squeezed the list of lists into a single list
- Solution: Only make disjoint if more than one interval
> Artifact interval bug

- CHANGELOG.md
- src/spyglass/lfp/v1/lfp_artifact.py
- src/spyglass/lfp/v1/lfp_artifact_difference_detection.py
Fixes #862, #850
- Assume no referencing if no `referencing` key present in `artifact_params`
- Only apply referencing if `ref_on` is True
- make `referencing a bool in `difference_artifact_detector` (no functional change)
> Fix non-referencing option in lfp artifact detection

- CHANGELOG.md
- src/spyglass/utils/dj_chains.py
- tests/utils/test_chains.py
Fixes failing pytests by making TableChains more robust to the case of no-link-found
> Fix failing chains pytests

- CHANGELOG.md
- src/spyglass/spikesorting/v1/figurl_curation.py
@rpswenson reported issues generating a FigURL with the following key
```python
from uuid import UUID
from spyglass.spikesorting.v1.figurl_curation import FigURLCuration
key = {'sorting_id': UUID('afeb8f45-a8cc-49f6-8609-6c26db8ff273')}
FigURLCuration.populate(key)
```
This PR addresses this issue by running a join before the fetch of upstream data.
Testing the result however lands on the following error. 
<details><summary>Stack</summary>
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 1
----> 1 from spyglass.spikesorting.v1.figurl_curation import FigURLCuration as F; from uuid import UUID; mk={'sorting_id': UUID('afeb8f45-a8cc-49f6-8609-6c26db8ff273')}; …
```
> Refine query of upstream tables on FigURL populate

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/workflows/lint.yml
- .github/workflows/publish-docs.yml
- .github/workflows/test-conda.yml
- .github/workflows/test-package-build.yml
- docs/build-docs.sh
- notebooks/README.md
- src/spyglass/position/v1/position_dlc_pose_estimation.py
I have already force-pushed to redeploy docs, removing bad versions `ref`, `[version]` and `0.4.1`.
These edits will address issues with redeploying next time around. This includes...
- Fixing references to renamed notebooks
- Omitting the docs branch from lint and test builds
- Fixing docstring in position
- Adding `<details>` block to bug template ... something I've routinely reformatted for submitted issues
> Edits for docs

- CHANGELOG.md
- src/spyglass/spikesorting/v0/spikesorting_curation.py
Fixes #884 
- `get_template_extremum` moved from `si.preprocessing` to `si.core` in v0.99.
> Update call to get_template_extremum

- CHANGELOG.md
- src/spyglass/utils/dj_helper_fn.py
- src/spyglass/utils/dj_mixin.py
Add ability to fetch nwb files as pynapple objects. Fixes #878 .
> Add pynapple support

- CHANGELOG.md
- src/spyglass/utils/dj_merge_tables.py
Fixes #920 
- Prior change in hash function allows possible duplicate entries in a merge part table  with different merge_ids
- during `_merge_insert`, prior to generation of UUID, check for presence of source primary key as an entry to avoid generating duplicates.
> Check for entry in merge part table prior to insert

- src/spyglass/common/__init__.py
PR #918 removed unused kachery tables from common.  This removes them from the __init__ file for common to avoid errors
> Quickfix for removal of old kachery tables

- src/spyglass/common/common_interval.py
- src/spyglass/decoding/v1/clusterless.py
- src/spyglass/decoding/v1/sorted_spikes.py
Strip will remove leading characters in any order.
Thanks to @gillespielab for finding this bug.
> Fix improper uses of strip

- CHANGELOG.md
- src/spyglass/common/common_ephys.py
- src/spyglass/common/common_nwbfile.py
- src/spyglass/common/common_position.py
- src/spyglass/common/common_usage.py
- src/spyglass/decoding/v0/clusterless.py
- src/spyglass/decoding/v1/waveform_features.py
- src/spyglass/lfp/analysis/v1/lfp_band.py
- src/spyglass/lfp/v1/lfp.py
- src/spyglass/linearization/v0/main.py
- src/spyglass/linearization/v1/main.py
- src/spyglass/position/v1/position_dlc_centroid.py
- src/spyglass/position/v1/position_dlc_orient.py
- src/spyglass/position/v1/position_dlc_pose_estimation.py
- src/spyglass/position/v1/position_dlc_position.py
- src/spyglass/position/v1/position_dlc_selection.py
- src/spyglass/position/v1/position_trodes_position.py
- src/spyglass/spikesorting/v0/spikesorting_curation.py
- src/spyglass/spikesorting/v1/curation.py
- src/spyglass/spikesorting/v1/metric_curation.py
- src/spyglass/spikesorting/v1/recording.py
- src/spyglass/spikesorting/v1/sorting.py
- src/spyglass/utils/dj_merge_tables.py
- src/spyglass/utils/dj_mixin.py
Resolves #907 with changes across many make funcs.
Our full solve for #861 may involve skipping some files that we can readily recompute. This PR adds a table to `common_nwbfile` to track how long it takes between `AnalysisNwbfile.create` and the end of the func that initiated this process. This will support decision making around recompute efforts.
The spikesorting v1 pipeline was unique for running `create` after the output had been generated... I think. This data is not going to be as accurate. Is it worth my time to find a new strategy to get the full processing time?
Currently, file size is in bytes, would we prefer MB?
> Add logging of AnalysisNwbfile creation time and file size

- CHANGELOG.md
- src/spyglass/utils/dj_merge_tables.py
Fixes #932
- Prevent error when calling `Merge.delete()` with no entries in restriction
> Fix bug on empty delete in merge table

- .github/ISSUE_TEMPLATE/bug_report.md
- CHANGELOG.md
Bug report template started it's `details` section with an end marker. Removing.
> Fix bug report template html

- CHANGELOG.md
- docs/build-docs.sh
- docs/mkdocs.yml
- docs/src/misc/index.md
- pyproject.toml
- src/spyglass/common/common_interval.py
- src/spyglass/position/v1/dlc_reader.py
- src/spyglass/settings.py
- tests/utils/test_mixin.py
1. Pytests were failing because of an unnecessary teardown line
2. Doc build was failing due to a bug(?) introduced in `mkdocstrings-python==0.9.1`. [Discussion](https://github.com/mkdocstrings/python/discussions/160). I pinned the requirement for now
3. Fixing the pin showed some cases of the build throwing warnings for existing docstrings. I fixec these cases.
> Fix tests/doc build

- CHANGELOG.md
- docs/mkdocs.yml
- docs/src/api/make_pages.py
- pyproject.toml
Received guidance from `mkdocstrings` developer [here](https://github.com/mkdocstrings/python/discussions/160) to allow us to unpin.
> Fix relative pathing for mkdocstrings>=1.9.1

- CHANGELOG.md
- docs/src/misc/mixin.md
- src/spyglass/decoding/v1/waveform_features.py
- src/spyglass/utils/dj_merge_tables.py
- src/spyglass/utils/dj_mixin.py
- Adds an edit to permit `Table << a << b`, by restricting self instead of returning free table
- Makes edits to docs to reflect instancing usage
> Permit multiple restrict_by

- CHANGELOG.md
- src/spyglass/position/v1/position_dlc_centroid.py
- src/spyglass/position/v1/position_dlc_orient.py
- src/spyglass/position/v1/position_dlc_pose_estimation.py
- src/spyglass/position/v1/position_dlc_position.py
- src/spyglass/position/v1/position_dlc_selection.py
Fixes #950 
- sources meters to pixels conversion from the camera device in the nwb
- make metadata from pre-existing spatial series optional
Fixes #961 
- avoid altering `analysis_file_name` in make functions before fetching needed data
> Allow dlc pipeline to run without prior position tracking

- CHANGELOG.md
- src/spyglass/common/common_behav.py
- src/spyglass/common/common_dio.py
- src/spyglass/common/common_ephys.py
- src/spyglass/common/common_session.py
- src/spyglass/common/common_task.py
- src/spyglass/common/populate_all_common.py
- src/spyglass/spikesorting/imported.py
- src/spyglass/utils/dj_merge_tables.py
- src/spyglass/utils/dj_mixin.py
- tests/common/test_behav.py
- tests/conftest.py
- tests/position/test_trodes.py
- A subset of tests were failing due to partial import from #957 
- These fails have been fixed by removing the previous PR's assumption of 1:1 relationships between populated and parent table
- This PR also removes `_no_transaction_make` for bare `make`, which is less explicit, but allows easier expansion of `populate_all_common` in the future
> Fix test fails related to #957

- CHANGELOG.md
- src/spyglass/position/v1/position_dlc_pose_estimation.py
- src/spyglass/position/v1/position_dlc_selection.py
Fixes #974 
`DLCPosVideo`
- get epoch directly from key to avoid missing interval error
- default to opencv for video writing
Other
- minor bug fix from #973
> Cleanup of dlc video

- CHANGELOG.md
- src/spyglass/utils/dj_mixin.py
#949 replaced `TableChain.join` with `cascade` to align with other `dj_graph` classes. This PR fixes a holdover instaces within `cautious_delete`
> Replace old `join` call with `cascade`

- src/spyglass/common/common_ephys.py
The only required fields for `nwbfile.add_electrode` are location and electrode group (https://pynwb.readthedocs.io/en/stable/pynwb.file.html#pynwb.file.NWBFile.add_electrode). Therefore some NWB files may not other fields such as `filtering`. Spyglass should check if these exist before trying to populate them; otherwise they should get the default value (e.g. `NULL`)
> Check existence of optional fields during `Electrode` table population

- CHANGELOG.md
- src/spyglass/spikesorting/analysis/v1/group.py
Small utility change.
- Currently `SortedSpikesGroup.get_firing_rate()` results in a default smoothing of the firing rate with a gaussian filter with 15ms sigma.
-  This PR adds argument `smoothing_sigma` to the function to allow user to choose different scale.
- No change to default functionality
> Add ability to set smoothing sigma in get_firing_rate

- CHANGELOG.md
- src/spyglass/decoding/v1/clusterless.py
- src/spyglass/decoding/v1/sorted_spikes.py
- src/spyglass/spikesorting/analysis/v1/group.py
Adds docstrings to methods in `SortedSpikesGroup` `ClusterlessDecodingV1` and `SortedSpikesDecodingV1`
> Add docstrings to SortedSpikesGroup and Decoding methods

- CHANGELOG.md
- notebooks/01_Insert_Data.ipynb
- notebooks/py_scripts/01_Insert_Data.py
- src/spyglass/common/common_nwbfile.py
Fixes #990 
- Corrects function call of `insert_sessions`  in `01_Insert_data.ipynb`
Resolves #953 
- Assigns new `obj_id` to files created by `AnalysisNwbfile.create()` to avoid overlap conflicts.
- Existing file errors resolved in dandi export process by `Export.prepare_files_for_export()`  (#956)
> Minor fixes

- CHANGELOG.md
- src/spyglass/common/common_nwbfile.py
#999 introduced an error to `AnalysisNwbfile.create()` by attempting to alter the object id of the incorrect file.  This fix corrects the alteration to be of the newly created analysis nwb file.
> Fix bug in change in analysis_file object_id

- CHANGELOG.md
- src/spyglass/decoding/v1/waveform_features.py
- src/spyglass/spikesorting/v0/spikesorting_recording.py
- src/spyglass/spikesorting/v1/recording.py
- src/spyglass/utils/dj_helper_fn.py
- src/spyglass/utils/dj_mixin.py
Changes to allow populate with `processes > 1` for tables that use parallel processing within their make function
Resolves #1000 
- Adds the property `parallel_make` to the mixin class
- By default = False
- Overwrite for in classes which spawn parallel processes within their `make` function
- Intercept populate calls in the `SpyglassMixin` class
- If multiple populate processes and  `parallel_make = True`
- Create non-daemonic pool of processes, each of which call `super().populate` for a single entry
ToDo:
> Non-daemon parallel populate

- CHANGELOG.md
- src/spyglass/spikesorting/v1/sorting.py
This fixes a bug in artifact masking step in the spike sorting pipeline. The artifact masking function expects to get as input the index of every sample to be zeroed, but the code was providing an interval of the indices instead for the artifacts that take place before the first artifact-free interval or after the last artifact-free interval.
> Fix artifact `list_triggers`

- CHANGELOG.md
- src/spyglass/position/v1/position_dlc_selection.py
Resolves #1010 
- add class specific method for `DLCPosV1.fetch_nwb()`
- explicitly avoid the `pose_eval_result` from going into `attrs` of `SpyglassMixin.fetch_nwb()`
- this avoids the SQL error
> remove problem key in DLCPosV1 fetch_nwb attrs

- CHANGELOG.md
- src/spyglass/__init__.py
- src/spyglass/cli/cli.py
- src/spyglass/common/common_dandi.py
- src/spyglass/common/common_filter.py
- src/spyglass/common/common_position.py
- src/spyglass/decoding/v0/clusterless.py
- src/spyglass/decoding/v0/core.py
- src/spyglass/decoding/v0/dj_decoder_conversion.py
- src/spyglass/decoding/v0/sorted_spikes.py
- src/spyglass/position/v1/position_dlc_training.py
- src/spyglass/utils/dj_mixin.py
Allow `ModuleNotFoundError` in all cases of failed imports
> #1016 - Allow `ModuleNotFoundError`

- CHANGELOG.md
- src/spyglass/spikesorting/analysis/v1/group.py
- src/spyglass/utils/dj_merge_tables.py
Changes to help speed up fetching nwb data through merge tables
- allow `Merge.fetch_nwb` to work with a restriction containing multiple entries and sources
- pre-check dependencies loaded to in `_ensure_dependencies_loaded`
- Avoid the overhead of the load call
- avoid redundant calls to `merge_get_parent` in `merge_restrict_class`
- refactor to single fetch_nwb call in `SortedSpikesGroup.fetch_spike_data`
- avoids repeatedly running the merge table restriction process to find source tables
> Merge table efficiency

- CHANGELOG.md
- src/spyglass/common/common_nwbfile.py
- src/spyglass/utils/dj_helper_fn.py
Preserves infrastructure for logging pending full analysis of this data.
Available to sit on or merge as we see fit.
> Disable AnalysisFile logging

- CHANGELOG.md
- src/spyglass/decoding/v1/core.py
- src/spyglass/spikesorting/analysis/v1/group.py
- src/spyglass/spikesorting/v0/spikesorting_populator.py
- src/spyglass/spikesorting/v1/recording.py
- Resolves #1022 
- Adds checks to the create_group methods for several tables to prevent unintentional insertion of new parts after creation
- `PositionGroup`
- `SortedSpikesGroup`
- `spikesorting.v1.SortGroup`
- minor change to `spikesorting_pipeline_populator` to restrict population to sort interval
> Group integrity

- CHANGELOG.md
- src/spyglass/position/v1/dlc_utils.py
This fixes two bugs introduced in 870 that had the potential to generate bad data
- `dlc_utils.py:red_led_bisector` was failing in case where LEDs 1 and 2 were present, but 3 was NaN. 
- `dlc_utils.py:Centroid`: one-point centroid had issues with partial NaNs, where NaNs were passed as `0`. 
Using the script below, I verified that no production data was impacted. 
<details><summary>Verification Script</summary>
```python
import os
import time
from datetime import datetime, timedelta
from pathlib import Path
from spyglass.position.v1.position_dlc_centroid import DLCCentroid as DC
from spyglass.position.v1.position_dlc_centroid import DLCCentroidParams as DCP
from spyglass.position.v1.position_dlc_orient import DLCOrientation as DO
from spyglass.position.v1.position_dlc_orient import …
```
> Bugfixes from 870

- CHANGELOG.md
- src/spyglass/spikesorting/analysis/v1/group.py
- src/spyglass/utils/dj_mixin.py
Quick fixes
- Fix bug from #1001 that prevented parallel populate processes on tables with `_parallel_make = False`
- Fix bug from #1027 
- during review, I moved `_get_spike_obj_name` from a class method to separate function
- this pr removes leftover `static_method` decorator
> Quick fix for parralel populate and spike unit naming

- CHANGELOG.md
- src/spyglass/spikesorting/utils.py
- src/spyglass/utils/dj_mixin.py
Streamlines logic of `get_group_by_shank` and adds missing returns #1054
> Revise get_group_by_shank

- CHANGELOG.md
- src/spyglass/utils/dj_helper_fn.py
`ensure_names` was generalized to a utils helper without removing the `self` arg, inadvertently always returning `None`
> #1053 bugfix

- CHANGELOG.md
- src/spyglass/spikesorting/utils.py
- src/spyglass/spikesorting/v0/spikesorting_artifact.py
- Resolves #1068
- makes consistent use  of `amplitude_threshold` name in `worker_ctx` dictionaries
- Adds `parallel_make` tag to `v0.ArtifactDetection`
> Spikesort artifact fixes

- CHANGELOG.md
- src/spyglass/decoding/v1/clusterless.py
- src/spyglass/spikesorting/v0/spikesorting_recording.py
- src/spyglass/spikesorting/v0/spikesorting_sorting.py
- src/spyglass/spikesorting/v1/sorting.py
Minor fixes in decode and spikesorting function calls
- fixes #1071 
- fetch `sort_interval_name` instead of `sort_interval`
- fixes #1047 
- Add check to `UnitWaveformFeaturesGroup.create_group` to avoid adding new parts to existing group
-  fix time slicing call in `ClusterlessDecodingV1.get_ahead_behind_distance`
- replace `np.int` with `np.int32` for future compatability
> Decode fixes

- CHANGELOG.md
- src/spyglass/utils/dj_graph.py
- src/spyglass/utils/dj_helper_fn.py
- src/spyglass/utils/dj_mixin.py
Collapsing the versions of `ensure_names` removed the mixin's default behavior of returning a list, meaning someone might ban the characters of a table name individually, rather than the name as a whole.
> Ban tables in distance restrict bugfix

- CHANGELOG.md
- docs/src/Features/Mixin.md
- src/spyglass/position/v1/position_dlc_training.py
- src/spyglass/spikesorting/v1/figurl_curation.py
- src/spyglass/spikesorting/v1/metric_curation.py
- src/spyglass/spikesorting/v1/sorting.py
- src/spyglass/utils/dj_graph.py
- src/spyglass/utils/dj_helper_fn.py
- src/spyglass/utils/dj_mixin.py
To address issues discussed in #1030, this PR allows the disabling of transaction protection.
This sacrifices full data integrity protection in order to avoid the bottleneck
> Allow disable transaction for select populates

- CHANGELOG.md
- src/spyglass/decoding/v1/waveform_features.py
- src/spyglass/spikesorting/spikesorting_merge.py
fixes #1082 
- prevents key errors when extracting `UnitWaveformFeatures` from a curated sorting with no units
fixes #1077 
- correct call to `get_spike_times` in `SpikeSortingOutput.get_spike_indicator`
> Prevent error from unitless spike group

- CHANGELOG.md
- pyproject.toml
- src/spyglass/spikesorting/analysis/v1/group.py
- src/spyglass/spikesorting/analysis/v1/unit_annotation.py
- src/spyglass/spikesorting/spikesorting_merge.py
- src/spyglass/spikesorting/v1/artifact.py
- src/spyglass/spikesorting/v1/recording.py
- src/spyglass/spikesorting/v1/utils.py
- tests/conftest.py
- tests/spikesorting/conftest.py
- tests/spikesorting/test_analysis.py
- tests/spikesorting/test_artifact.py
- tests/spikesorting/test_curation.py
- tests/spikesorting/test_figurl.py
- tests/spikesorting/test_merge.py
- tests/spikesorting/test_metric_curation.py
- tests/spikesorting/test_recording.py
- tests/spikesorting/test_sorting.py
- tests/spikesorting/test_utils.py
This PR adds tests for `spikesorting.v1` using existing notebooks
A notable absence is full testing of FigURL utilities pending discussion of how to best interface for CI/CD
<details><summary>Coverage report</summary>
```
---------- coverage: platform linux, python 3.9.19-final-0 -----------
Name                                                       Stmts   Miss  Cover   Missing
----------------------------------------------------------------------------------------
src/spyglass/spikesorting/analysis/v1/group.py                92     34    63%   76-78, 107-126, 176, 187-195, 199, 214, 232-247, 277, 292
src/spyglass/spikesorting/analysis/v1/unit_annotation.py      41      2    95%   75, 138
src/spyglass/spikesorting/imported.py                         64     35    45%   49-58, 64, 70, …
```
> Add tests for spikesorting

- CHANGELOG.md
- src/spyglass/linearization/v1/main.py
V0 had a parameter for edge_map in the track linearization but V1 does not. The edge_map allows the user to combine linear edges in the 1D space.
> Add edge map parameter to track linearization

- CHANGELOG.md
- src/spyglass/position/v1/position_dlc_centroid.py
Fixes #1107:
- add position and velocity object to the analysis nwb file before inserting to `AnalysisNwbfile`
- prevents mismatched checksum/size from altering file after insert
> Add objects to analysis file before insert

- CHANGELOG.md
- src/spyglass/utils/dj_graph.py
- tests/conftest.py
DataJoint [#1184](https://github.com/datajoint/datajoint-python/pull/1184) renamed `unite_master_parts` to `topo_sort`. This PR runs a `try/except` on this import until they make a release and we adjust our pin.
> Revise datajoint import name

- CHANGELOG.md
- src/spyglass/spikesorting/v0/spikesorting_curation.py
Fixes #1110 
- avoids restricting `v0.Curation` by secondary keys which contain dictionary blobs (which led to SQL errors)
> Fix Curation primary key creation from spikesorting key

- CHANGELOG.md
- src/spyglass/common/common_ephys.py
- Fixes #1121: Reduces number of fetches
- `common_ephys.py`: Introduce a region_ids_dict so we don't make redundant calls to the database
> speed up electrodes import

- CHANGELOG.md
- src/spyglass/utils/dj_merge_tables.py
- `Merge.extract_merge_id()` was introduced in #1086 to help allow restriction by Merge table or parent table in `Merge.fetch_nwb()`
- The logic of this function created a And restriction when multiple merge ids were present in the restriction
- This would always lead to an empty table when applied since an entry can't match 2 different merge_id values
- This PR changes the restriction returned by `Merge.extract_merge_id()` to or logic to allow proper function.
> Switch to or logic when multiple merge ids in restriction

- CHANGELOG.md
- src/spyglass/common/common_task.py
- tests/common/test_behav.py
Fixes #1119 
- make the null value when getting `config_tasks` an empty list to prevent non-iterable error
Fixes #1122 
- alter warning to avoid error
Fixes #1123 
- Update test of position interval map for updated null key insert
> Fix null config_tasks value

- CHANGELOG.md
- src/spyglass/common/common_task.py
- src/spyglass/spikesorting/v1/metric_curation.py
Fixes waveform_params dict in metric curation so that the `sparse` keyword is handled when set.
- Fixes #1127
> Fix waveform params in metric curation

- CHANGELOG.md
- pyproject.toml
- src/spyglass/utils/database_settings.py
- src/spyglass/utils/dj_graph.py
- src/spyglass/utils/dj_merge_tables.py
- tests/utils/test_graph.py
This PR...
- Removes a redundant `topological_sort` in long distance restrictions
- Fixes `print` -> `logger.info`
- Fixes `position_linearization` -> `linearization`
> Long distance restr fix

- CHANGELOG.md
- src/spyglass/position/v1/position_dlc_centroid.py
#1112 introduced a bug in how objects were added to the analysis nwb file in `DLCCentroid.populate()`.  This corrects this error.
> Quickfix: typo in adding objects to nwb

- CHANGELOG.md
- src/spyglass/common/common_usage.py
- src/spyglass/utils/dj_graph.py
- src/spyglass/utils/nwb_helper_fn.py
I ran `common_usage` tests and addressed issues from #1095
> Additional export fixes

- CHANGELOG.md
- tests/conftest.py
- tests/linearization/test_lin.py
- tests/position/test_trodes.py
- tests/spikesorting/conftest.py
- tests/spikesorting/test_curation.py
- tests/spikesorting/test_merge.py
pytests with explicit hashes passed locally but failed in gh-actions. In this PR, I remove those stored hashes in favor of comparing key-value pairs to remove any low-level causes of mismatching hashes.
> Remove stored hashes from tests

- .github/workflows/test-conda.yml
- CHANGELOG.md
Mambaforge is being sunset (see https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/) because miniforge is now essentially the same. This PR removes the mambaforge variant and switches to using miniforge for the tests.
> Remove mambaforge from tests

- CHANGELOG.md
- src/spyglass/utils/dj_graph.py
In small scale tests, the old and new topological sort mechanisms behaved the same, but failed with an alias node in #1161. 
This PR re-introduces the old logic pending release of DataJoint 0.14.3. Ordering isn't exactly the same across versions, but this would only cause problems if someone upgraded within a python session
> Fix topological sort logic

- .github/workflows/test-package-build.yml
- CHANGELOG.md
- environment.yml
- environment_dlc.yml
- pyproject.toml
We previously restricted the maximum python version to be less than 3.10 due to the issue #408. This has now been fixed (see https://github.com/datajoint/datajoint-python/issues/1007) and datajoint is tested up to python 3.12. Therefore, I propose we allow up to 3.12 as well.
We also restricted numpy due to issues with numba (https://github.com/LorenFrankLab/spyglass/pull/462). Numba is now compatible with all recent numpy versions (https://numba.readthedocs.io/en/stable/user/installing.html#version-support-information) although numpy 2.0 only has binary compatibility.
This PR will enable users to use more up to date packages with spyglass (see https://github.com/LorenFrankLab/spyglass/issues/831 for example).
Changes:
+ allow python versions up to 3.12
+ add testing for python versions …
> Allow python <3.13 and remove numpy pin

- CHANGELOG.md
- src/spyglass/common/common_ephys.py
Fixes #1171
- add no_transaction flags to `common_ephys.LFP`
> No transact insert v0 lfp

- .gitignore
- CHANGELOG.md
- src/spyglass/common/common_behav.py
- src/spyglass/position/v1/dlc_utils_makevid.py
- src/spyglass/position/v1/position_dlc_selection.py
This PR addresses #1160 by allowing the `make_video` process to continue without a `PosIntervalMap` entry. 
This PR is also a partial address of #1157 by reverting to `matplotlib` as the default video processor, and saves the output as temp files. OpenCV as a tool for reading frames was very memory hungry (300gb for 10k frames) during testing of batch processing, and was probably memory leaking somewhere. Switching to a two step process that saves each frame to disk, RAM usage hovered ~7gb over baseline with the current batch size. More work could be done to dial in these defaults to optimize video creation time based on available resources
> `DLCPosVideo`: Use provided epoch, multithread matplotlib

- src/spyglass/utils/dj_mixin.py
- Catches error case in hashing where only single key is being populated
- Fixes #1177 typo
> No transact bug

- CHANGELOG.md
- src/spyglass/common/common_device.py
Fixes issue raised in #1074 where the dictionary `config_probes` was not properly passe
> Quickfix: pass config_probe

- CHANGELOG.md
- src/spyglass/spikesorting/v0/spikesorting_curation.py
- src/spyglass/spikesorting/v0/spikesorting_recording.py
Resolves #1186
- Turns of populate transactions for:
- `spikesorting.v0.Waveforms`
- `spikesorting.v0.QualityMetrics`
> No transactions v0 spikesorting pipeline

- CHANGELOG.md
- src/spyglass/spikesorting/v0/spikesorting_artifact.py
- src/spyglass/spikesorting/v1/artifact.py
Fixes #1176
- In artifact detection, clip intervals going past the valid timestamps to the last valid timepoint
- prevents error when artifact interval window buffer goes past the end of the timestamps
> Limit spikesorting artifacts to valid timestamps

- CHANGELOG.md
- docs/src/ForDevelopers/Management.md
- src/spyglass/common/common_interval.py
- src/spyglass/utils/dj_mixin.py
Fixes #1194 (solution 2)
- remove `IntervalList` cleanup from `Mixin.delete()`
- Add `IntervalList.cleanup()` to documentation for nightly cron job
> Cleanup IntervalList orphans in weekly job only

- CHANGELOG.md
- notebooks/05_Export.ipynb
- notebooks/py_scripts/05_Export.py
The DANDI Docs URL recently changed from www.dandiarchive.org/handbook to docs.dandiarchive.org
> Update URL for DANDI Docs

- CHANGELOG.md
- src/spyglass/common/populate_all_common.py
- src/spyglass/utils/dj_helper_fn.py
Fixes #1204, #872
- Merge tables not guaranteed to be declared before imported by their parent_source make call
- Can cause error in fresh database when tries to declare within the make transaction
- Done to avoid circular imports
- Add new util `declare_all_merge_tables` which imports all core spyglass merge tables to ensure declaration
- Run during `populate_all_common` (part of `insert_sessions`) to ensure tables are declared once data is in the database
> Ensure merge tables declared in new database

- CHANGELOG.md
- src/spyglass/spikesorting/v1/curation.py
4x speedup on `get_sorting` method.
+ Eliminate repeated calls to recording.get_times()
+ Use pandas dataframe method `itertuples`
> Speedup get_sorting

- CHANGELOG.md
- src/spyglass/spikesorting/analysis/v1/group.py
Previous fix failed to properly filter the units for v1 pipeline spike sorting data. This rectifies that. Fixes #1236 .
> Fix filtering on labels

- CHANGELOG.md
- src/spyglass/spikesorting/analysis/v1/group.py
- tests/spikesorting/test_utils.py
- Fixes #1260 
- enable `time_slice` to be either a `slice` or a `list` of start and stop time
- Update docstring
> Fix mismatch in `time_slice` typing in `SortedSpikesGroup.fetch_spike_data`

- CHANGELOG.md
- src/spyglass/spikesorting/v0/spikesorting_curation.py
Transactions for `CuratedSpikeSorting` were holding long table locks in frank lab database.  Turning off table transactions to avoid.
> Quickfix: Turn off transactions for CuratedSpikeSorting

- src/spyglass/spikesorting/v0/spikesorting_curation.py
- src/spyglass/spikesorting/v0/spikesorting_recording.py
`_use_transaction` was missing leading underscore in v0 spikesorting tables preventing disableing transactions by default
- Fixes #000: How this PR fixes the issue
- `path/file.py`: Description of the change
- `path/file.py`: Description of the change
- Fixes #000: How this PR fixes the issue
- `path/file.py`: Description of the change
- `path/file.py`: Description of the change
> Quickfix: spikesorting vo _use_transaction

- CHANGELOG.md
- docs/src/ForDevelopers/UsingNWB.md
- src/spyglass/common/common_behav.py
- src/spyglass/common/common_task.py
- src/spyglass/common/populate_all_common.py
- src/spyglass/lfp/lfp_electrode.py
- src/spyglass/lfp/lfp_imported.py
- src/spyglass/position/v1/dlc_utils.py
- tests/lfp/test_lfp.py
Resolution of several issues regarding nwb ingestion by other groups.
- Fixes #1224 
- When finding videos for population of `VideoFile` get all `ImageSeries` objects in the nwb file rather than looking specifically in `nwbf.processing['video']`
- Less arbitrarily restrictive for other labs' nwb generation  
- Fixes #1221 
- Allow complete ingestion of task tables with more than one row
- Fixes #1229 
- Modify definition of `ImportedLFP`
- No longer dependent on `AnalysisNwbfile`
- Instead, expected to point to an e-series object containing lfp data in the raw nwb  
- Implement `ImportedLFP._no_transaction_make`
- Find  LFP objects in the raw file and the eseries contained within. For each object
- Determine the electrodes of the eseries, making a new `LFPElectrodeGroup` entry if …
> Generalizations for nwb ingestion

- CHANGELOG.md
- src/spyglass/common/populate_all_common.py
- src/spyglass/lfp/lfp_electrode.py
- src/spyglass/lfp/lfp_imported.py
- tests/common/test_behav.py
- tests/lfp/test_lfp.py
Fixes several errors in ImportedLFP ingestion
- object search
- `LFPElectrodeGroup.LFPElectrode` entry
- key source
Adds Test of LFP ingestion:
- added a pynwb `LFP` object to the testing rec file. Is now ingested in the test fixtures
- implement `test_pop_imported_lfp` and remove skiptest
> LFP Import fix

- src/spyglass/common/common_behav.py
- Fixes: 
- `src/spyglass/common/common_behav.py`: changed line 339, call to upper had no parentheses
- [ no ] This PR should be accompanied by a release: (yes/no/unsure)
- [ X ] N/A If release, I have updated the `CITATION.cff`
- [ no ] This PR makes edits to table definitions: (yes/no)
- [ X ] N/A If table edits, I have included an `alter` snippet for release notes.
- [ X ] N/A If this PR makes changes to position, I ran the relevant tests locally.
- [ no ] I have updated the `CHANGELOG.md` with PR number and description.
- [ no ] I have added/edited docs/notebooks to reflect the changes
> Fix call to 'upper' in common_behav.py

- CHANGELOG.md
- src/spyglass/spikesorting/analysis/v1/group.py
- src/spyglass/utils/dj_merge_tables.py
- tests/position/test_pos_merge.py
Fixes #1319 
- In `Merge.fetch_nwb( return_merge_ids=True)` ensure that the merge ids are returned in the order corresponding with the nwb files
- Relevant for correct function of `SortedSpikeGroups.fetch_spike_data(key, return_unit_ids=True)`
Other:
- add `return_unit_ids` option to methods of `SortedSpikesGroup`
- `get_spike_indicator`
- `get_firing_rate`
> Returned merge_id consistency for Merge.fetch_nwb 

- CHANGELOG.md
- src/spyglass/spikesorting/v1/recording.py
Commits in review of #1310 negated the fix for #1309 . This reverts to accurately check for `channel_name` column in electrodes table of nwb file
> Fix spikeinterface channel names

- CHANGELOG.md
- src/spyglass/common/common_behav.py
- src/spyglass/common/common_dio.py
- src/spyglass/lfp/lfp_imported.py
In ingesting a file from DandiSet 001457, I hit a number of errors related to ingesting empty timeseries
Electing not to add coverage for cases not covered by the demo data. If needed, I can look into monkeypatching these `make`s
> Skip empty timestamp objs

- .github/codecov.yml
- .github/pull_request_template.md
- CHANGELOG.md
This PR adds a [coverage target](https://docs.codecov.com/docs/gitlab-3-customizing-codecov#set-coverage-standards) to prevent a failing test on small edits. PRs that add more than 1-2% to the code base will trigger this fail
This PR also simplifies the checklist below for a more streamlined pattern of `If A, B // If C, D // changelog`
> PR QoL: codecov fail limit, PR template edits

- CHANGELOG.md
- src/spyglass/position/v1/position_dlc_position.py
- src/spyglass/position/v1/position_dlc_selection.py
A couple of minor errors were introduced in PR #870.
Parameter handling improvements:
* In `src/spyglass/position/v1/position_dlc_selection.py`, the code now ensures that `pose_estimation_params` is always a dictionary, preventing potential errors when accessing its values.
* In `src/spyglass/position/v1/position_dlc_position.py`, the interpolation parameters are now correctly fetched from `interp_params` instead of being tied to the existence of the `interpolate` flag, improving clarity and flexibility in parameter usage.
Default value corrections:
* The default value for the `debug` parameter in the position estimation call within `src/spyglass/position/v1/position_dlc_selection.py` has been changed from `True` to `False`, aligning with expected production behavior.
> Minor DLC Fixes

- CHANGELOG.md
- docs/mkdocs.yml
- docs/src/api/ingestion_mapping_generate.py
- src/spyglass/common/common_device.py
- src/spyglass/common/common_dio.py
- src/spyglass/common/common_ephys.py
- src/spyglass/common/common_interval.py
- src/spyglass/common/common_lab.py
- src/spyglass/common/common_nwbfile.py
- src/spyglass/common/common_session.py
- src/spyglass/common/common_subject.py
- src/spyglass/common/common_user.py
- src/spyglass/common/populate_all_common.py
- src/spyglass/data_import/insert_sessions.py
- src/spyglass/spikesorting/imported.py
- src/spyglass/utils/dj_mixin.py
- src/spyglass/utils/nwb_helper_fn.py
- tests/common/test_device.py
- tests/conftest.py
- tests/position/v1/test_import.py
This PR makes updates to existing work on NWB ingestion by...
- Addressing failing tests
- Building the mapping doc on mkdocs build
- Handling inserts as dicts, to allow multi-table inserts (i.e., TableA triggers inserts for TableA and TableB)
- Quieting false-positive 'accept divergence' issues (i.e., normalize defaults before entry, skip empty nullable inserts)
- Standardizing the output format: `{nwbfile} inserts {count} into {table}`
Adds `SpyglassIngestion` to ...
- `Raw`
- `DIOEvents`
To do:
- Makes user-facing changes to logging - does that require edits to docs?
- New approach changes an `IntervalList` insert from `cautious_insert` -> vanilla `insert`
- Should this motivate an override of `insert`?
- Does `SpyglassIngestion` need to check for a `cautious_insert` method?
- [?] If …
> Standardize import: tests, map on doc build, allow multi-table insert, quiet false-positive divergence
