devel/garbage_collection.py, environment.yml, setup.py
Added devel/garbage_collection.py which is a WIP.
It shows how the garbage collection will be done. However, the piece missing is actually figuring out which hashes to keep. I didn't do that yet because I am having trouble populating the database - not able to read the nwb file now (ndx_franklab_novela may have changed?)
Also:
my conda was having trouble loading ghostipy -- so I removed it as a conda dependency, and kept it as a pip dependency
=> WIP: garbage collection

src/nwb_datajoint/common/common_behav.py
fixed name of nwb associated_files field
=> edit StateScriptFile schema to enable population

src/nwb_datajoint/common/common_nwbfile.py
=> Dataframe fix

tests/datajoint/_datajoint_server.py
=> Fix broken hither import

environment.yml
Updating pynwb and hdmf will also help resolve a conda environment conflict with the latest https://github.com/LorenFrankLab/ndx-franklab-novela
=> Use the latest pynwb and hdmf

src/nwb_datajoint/common/common_ephys.py, src/nwb_datajoint/common/common_spikesorting.py, src/nwb_datajoint/common/common_task.py
Added code to define target_hemisphere field in ElectrodeGroup table based on targeted x coordinate in electrode group metadata
=> Define target hemisphere field in ElectrodeGroup table

src/nwb_datajoint/common/common_spikesorting.py
use z-score OR amplitude threshold rather than both in artifact removal
=> artifact removal typo fix

environment.yml
So that we can take advantage of latest bug fixes
=> Install spikeinterface from Github

docs/developer_notes.md
=> fix naming of default parameter insertion method

franklab_scripts/nightly_cleanup.py, src/nwb_datajoint/cli/cli.py, src/nwb_datajoint/common/__init__.py, src/nwb_datajoint/common/common_ephys.py, src/nwb_datajoint/common/common_interval.py, src/nwb_datajoint/figurl_views/SpikeSortingRecordingView.py, src/nwb_datajoint/spikesorting/__init__.py, src/nwb_datajoint/spikesorting/sortingview.py, src/nwb_datajoint/spikesorting/sortingview_helper_fn.py, src/nwb_datajoint/spikesorting/spikesorting_artifact.py, src/nwb_datajoint/spikesorting/spikesorting_curation.py, src/nwb_datajoint/spikesorting/spikesorting_recording.py, src/nwb_datajoint/spikesorting/spikesorting_sorting.py
Addresses issues #171 based on changes made as discussed in #164. Also fixes #150 and #143
Tested up to `SpikeSorting` table.
=> Fix import errors in `spikesorting` submodule

src/nwb_datajoint/spikesorting/MergedSortingExtractor.py, src/nwb_datajoint/spikesorting/spikesorting_curation.py
Implement this as a class so that it can be reconstructed from a dict.
=> implement MergedSortingExtractor

examples/cli_examples/create_session_group.py, examples/cli_examples/create_spyglass_view.sh, examples/cli_examples/insert_sort_interval.py, examples/cli_examples/readme.md, examples/cli_examples/set_sort_groups_by_shank.py, src/spyglass/cli/cli.py, src/spyglass/common/common_session.py
This folds in @magland's session group code.
=> Scratchrealm update session group

src/spyglass/spikesorting/spikesorting_sorting.py
same as #208, just in a different place
=> Check recording type before concat

src/spyglass/spikesorting/spikesorting_sorting.py
=> Move concatenation of recording outside artifact removal step

src/spyglass/spikesorting/spikesorting_sorting.py
=> Find artifact times2

src/spyglass/spikesorting/spikesorting_sorting.py
See issue #222. Has been tested locally.
=> Import sortingcomponents fxns one by one

src/spyglass/spikesorting/spikesorting_recording.py
Mountainsort4 errors out for sort groups with one channel. This pull request makes a change to set_group_by_shank to allow the user to avoid defining sort groups for unitrodes, to avoid this downstream sorting error.
=> Omit unitrodes when setting sort group by shank

src/spyglass/spikesorting/spikesorting_recording.py
Currently spikeinterface constrains the channel locations to be on a plane (i.e. 2D). This doesn't play nice with some of our nwb files, which contain both tetrodes (whose locations are given in the xz plane) and probes (whose locations are given in the xy plane). As a result, the downstream visualization (e.g. sortingview waveform plot) is compromised. This is a workaround that makes up fake channel locations if the sort group is a tetrode.
related:
https://github.com/SpikeInterface/spikeinterface/issues/605
=> Make correct channel locations for tetrode

src/spyglass/common/common_ephys.py, src/spyglass/common/common_region.py, src/spyglass/spikesorting/spikesorting_recording.py
This pull request adds a table to match sort groups with targeted locations from nwb file metadata.
=> add SortGroupTargetedLocation table

src/spyglass/common/common_ephys.py
This fixes the SampleCount table so that new records are inserted for each Nwbfile.
=> Added insert to SampleCount

src/spyglass/spikesorting/spikesorting_artifact.py
phil helped me edit lines 224-227 in spikesorting_artifact.py to remove duplicate calculation of artifact window indicies
=> increase speed of artifact detection

.github/ISSUE_TEMPLATE/bug_report.md, README.md, environment.yml, src/spyglass/spikesorting/sortingview.py, src/spyglass/spikesorting/sortingview_helper_fn.py, src/spyglass/spikesorting/spikesorting_recording.py, src/spyglass/spikesorting/spikesorting_sorting.py
new `sortingview` uses `kachery-cloud` not `kachery-daemon`
=> Migrate to new sortingview

src/spyglass/spikesorting/sortingview.py
remove extra "include_curation" argument in SortingviewWorkspace
=> Fix SortingviewWorkspace bug

src/spyglass/spikesorting/spikesorting_recording.py
3 extra occurrences of spikeinterface.toolkit.preprocessing changed to just spikeinterface.preprocessing. Confirmed with @khl02007 before making these changes.
=> Change "st.preprocessing" to "si.preprocessing"

src/spyglass/spikesorting/spikesorting_sorting.py
adds tempdir as  sorting parameter within SpikeSorting make function
=> automatically uses right tempdir for sorting

src/spyglass/spikesorting/sortingview_helper_fn.py
Views are now individually defined and added, including cross correlograms
A placeholder is added for the similarity matrix
@MichaelCoulter
=> Update creating spikesortingview

environment.yml
=> Install pyfftw from conda-forge instead of pip

src/spyglass/common/common_behav.py
check statescript file description before import to avoid duplicate error.
=> Statescript import fix

src/spyglass/decoding/visualization.py
For add-decoding branch: handle using environment directly instead of classifier when binning linpos overlay
=> Update 1d decode visualization

src/spyglass/common/nwb_helper_fn.py
This pull request adds a function to nwb_helper_fn.py that allows a user to change the group permissions on their analysis nwb files.
=> add function to change analysis nwbf group permissions

README.md
added note in readme about need to install cupy for decoding.
=> add note about cupy

src/spyglass/common/common_filter.py
=> Fix `ghostipy` import error

notebooks/1_spikesorting.ipynb, notebooks/2_curation.ipynb, notebooks/3_lfp.ipynb, notebooks/6_Extract_Mark_indicators.ipynb, notebooks/7_Decoding_with_GPUs_on_the_GPU_cluster.ipynb, notebooks/9_2D_Clusterless_Decoding.ipynb
=> fix-doc-issues-with-notebooks

src/spyglass/__init__.py, src/spyglass/spikesorting/__init__.py, src/spyglass/spikesorting/curation_figurl.py, src/spyglass/spikesorting/sortingview.py, src/spyglass/spikesorting/sortingview_helper_fn.py, src/spyglass/spikesorting/spikesorting_curation.py
code for generating new figURL for manual curation. creates part table within SortingviewWorkspace
=> New manual curation and num_spikes metric

src/spyglass/spikesorting/spikesorting_curation.py
=> Fix spikeinterface refactor

CITATION.cff, docs/developer_notes.md, pyproject.toml
There have been a number of changes in spyglass since to 0.1.0 release on PyPI, and there are a few larger-scale changes coming soon from @khl02007 and me. Before we make those changes, I think it would be good to make a new release that includes the changes made so far.
In this PR, I updated the version string and added developer notes for making a release.
=> Update version to 0.2.0

tests/test_insert_beans.py
This PR disables a broken test. A different PR will fix the test.
=> disable-test_insert_session

pyproject.toml
=> limit-python-to-3.9-in-pyproject_toml

src/spyglass/spikesorting/sortingview.py, src/spyglass/spikesorting/sortingview_helper_fn.py
- Fixes import error reported in #417
- Future fix will remove `SortingviewWorkspace` table
=> Fix import error due to deprecated `sv.Workspace`

src/spyglass/utils/dj_helper_fn.py
=> Fix import of common_nwbfile

src/spyglass/common/common_ephys.py, src/spyglass/spikesorting/spikesorting_recording.py
=> Fix references to changed Probe primary key

src/spyglass/common/common_device.py
=> Use title case for adc_circuit and data_acquisition_device_amplifier

src/spyglass/common/common_device.py
Fix #432 
Also fix two other bugs related to adding a new DataAcquisitionDevice and a new ProbeType
=> Fix probe mfr None issue

src/spyglass/spikesorting/spikesorting_recording.py
=> Fix bug with spike sorting and probe

CHANGELOG.md, CITATION.cff, pyproject.toml
Update version for pypi release
Also add initial CHANGELOG. A more full CHANGELOG will be added next.
=> Update version to 0.3.4

src/spyglass/spikesorting/spikesorting_curation.py
This pull request changes the input to the whitening function to avoid an error when using the int datatype. This solves issue #445.
=> add integer scale for whitening recording

src/spyglass/spikesorting/spikesorting_sorting.py
=> Remove whiten parameter

src/spyglass/spikesorting/spikesorting_curation.py
=> Change whiten to float16 for metric computation

src/spyglass/spikesorting/spikesorting_sorting.py
Don't whiten if you are doing clusterless
=> Move whiten

config/add_dj_collaborator.py, config/add_dj_guest.py
This add scripts in the config directory to add guests and collaborators as users who can either see everything but not edit (guest) or see everything and edit their own schema.
=> Add guest users

src/spyglass/common/common_ripple.py
Fixes #477 
Note that this still depends on the old position pipeline at the moment
=> Change LFP imports to new LFP pipeline

src/spyglass/spikesorting/spikesorting_sorting.py
Currently, whitening happens even if sorter_params["whiten"] is False, and happens twice if sorter_params["whiten"] is True (once before passing data to the sorter, and once after). With these changes, whitening happens once if sorter_params["whiten"] is True, and does not happen if sorter_params["whiten"] is False.
=> Handle whiten

notebooks/Spyglass_kachery_setup.ipynb, src/spyglass/sharing/sharing_kachery.py
updates to kachery code to allow for multiple zones
=> Kachery_updates

environment.yml, environment_position.yml, pyproject.toml, src/spyglass/common/common_position.py
Skan was causing some installation issues and not used except in defining the track graph for linearization
=> Remove skan and polygon selector

src/spyglass/spikesorting/spikesorting_sorting.py
=> remove extra parameter for clusterless thresholder

src/spyglass/lfp_band/v1/lfp_band.py
Addresses #587 by updating the `LFPBandV1.fetch1_dataframe` method. Recent changes to `LFPBandV1` modified the name of the associated nwb object from "filtered_data" to "lfp_band" and this PR reflects those.
=> update LFPBandV1 fetch1_dataframe

notebooks/03_lfp.ipynb
This pull request changes the imports and tables referenced in `03_lfp.ipynb` to be up-to-date with recent changes to the LFP pipeline.
=> Update 03_lfp notebook to reflect LFP changes

src/spyglass/lfp/v1/lfp_artifact.py, src/spyglass/lfp/v1/lfp_artifact_MAD_detection.py, src/spyglass/lfp/v1/lfp_artifact_difference_detection.py
Made some adjustments 
- wrapping comments at 88
- doing all insertions at once - should this be a LookUp table?
- removing conditional blocks by adding conditional assignment (eg, `x = y if bool else z`) or early termination or migrating checks over multiple variables to an embedded func
- and adding `*args, **kwargs` so that unnecessary params will be ignored when running the artifact detection algorithm
- using `key.update` to reduce number of operations
- condensing multiple warnings to a formatting string
=> LFP artifact optimizations

src/spyglass/spikesorting/spikesorting_artifact.py
Fixes https://github.com/LorenFrankLab/spyglass/issues/492
=> Handle case where there is only one artifact interval

src/spyglass/decoding/visualization_1D_view.py
This speeds up creation of the 1D decode visualization in figurl by using a more efficient algorithm.
=> Avoid for loop and use searchsorted

src/spyglass/spikesorting/__init__.py, src/spyglass/spikesorting/spikesorting_populator.py
Addresses issues #634. 
- Creates a function `spikesorting_pipeline_populator` which takes in a session name, interval, and set of computed table parameter names. The function then automatically populates the spikesorting and curation tables for all sort groups in this interval
- Makes a new table `SpikeSortingPipelineParameters` which stores sets of parameter names for the spikesorting and curation pipelines.  The primary key for this table can be passed to  `spikesorting_pipeline_populator` and the corresponding sets of parameters will be used. Useful for storing default sets or sets used consistently in a given project.
=> Spiksorting pipeline populator

src/spyglass/spikesorting/spikesorting_populator.py
Fix key reference in the autocuration table
=> Fix key error

examples/parallel_spikesorting_tutorial.ipynb
Create a tutorial for the `spikesorting_pipeline_populator` function and demonstrate how to use dask to run parallel calls across different sessions and intervals
=> Add tutorial for parallel spikesorting pipeline

.gitignore, docs/src/contribute.md, notebooks/12_Ripple_Detection.ipynb, src/spyglass/common/common_behav.py, src/spyglass/common/common_lab.py, src/spyglass/common/common_nwbfile.py, src/spyglass/common/common_position.py, src/spyglass/common/common_session.py, src/spyglass/common/populate_all_common.py, src/spyglass/data_import/insert_sessions.py, src/spyglass/lfp/v1/lfp.py, src/spyglass/position/v1/dlc_utils.py, src/spyglass/position/v1/position_trodes_position.py, src/spyglass/ripple/v1/ripple.py, src/spyglass/settings.py, src/spyglass/utils/dj_merge_tables.py, src/spyglass/utils/nwb_helper_fn.py, tests/conftest.py
This PR addresses #613 with table alteration proposals and corresponding `make` adjustments.
Once approved, I'll schedule a time to make these alterations to the production database. We should hold off on merging this until those changes are made.
=> #613 - RawPosition handle multiple pynwb position objects

src/spyglass/common/common_interval.py, src/spyglass/common/common_region.py
Fixes minor bugs within the with calls made by `insert_session`
=> Insert session debug

.github/pull_request_template.md, CITATION.cff, docs/src/contribute.md, src/spyglass/common/common_nwbfile.py
Adding edits to contribution docs to reflect current usage.
Adding norms per #531. If accepted, I will check with authors and prune stale branches. 
If merged, I will force-push to `documentation` to remove erroneous versions and push a new tag to trigger docs publish.
=> Contrib docs edits

src/spyglass/common/common_filter.py
Populating of LFPV1 hit errors after recent refactor commit #654.  Reverts lines which broke on use to prior functionality. Mostly issues with shape, or pass by reference (which altered original values).
=> Minor bugs in lfp filtering

src/spyglass/spikesorting/spikesorting_curation.py
Fixes #718 
- SpikeInterface has a bug in nearest neighbor metric calculations in a warning definition (see original issue).  
- This warning is only triggered when the number of spikes is less than `min_spikes`.
- This PR checks for this condition before calling the spikeinterface function, and if it occurs, skips calling the function and directly enters the `nan` value the function would have returned
- No change to intended output, just avoids the bug
=> Avoid bug in spikeinterface for low spikecounts

CHANGELOG.md, dj_local_conf_example.json, notebooks/21_Position_DLC_1.ipynb, notebooks/py_scripts/21_Position_DLC_1.py, src/spyglass/common/common_behav.py, src/spyglass/position/v1/dlc_utils.py, src/spyglass/position/v1/position_dlc_project.py, src/spyglass/settings.py, src/spyglass/spikesorting/spikesorting_curation.py, src/spyglass/spikesorting/v1/sorting.py
- Migrate DLC path variables to `settings.py`
- Rename DLC vars: `DLC_X_PATH` -> `DLC_X_DIR`
- Add note on vars and and multicam to notebook
- Clean up spike sorting, grab waveform var from settings.py
This PR contains an updated version of notebook 21 from @emreybroyles
=> Env variables for DLC

src/spyglass/sharing/__init__.py, src/spyglass/sharing/sharing_kachery.py
Adds helper function for adding data to kachery sharing tables
=> Helper function for adding data to kachery

src/spyglass/position/v1/position_trodes_position.py
Fixes #739 
There is a mismatch in number of position time points and frames in upsampled position data, which causes an error when creating a dataframe with both.
This PR adds a check during `fetch1_dataframe` to see if the data is upsampled. If so, it does not add the frame info.
=> Check for upsampled data in trodes fetch dataframe

src/spyglass/lfp/lfp_electrode.py
=> Handle numpy arrays in `create_lfp_electrode_group`

src/spyglass/utils/dj_merge_tables.py, src/spyglass/utils/dj_mixin.py
=> WIP: Mixin resolves _nwb_table attr for Merge

tests/common/test_position.py
Related to single LED halving the data bug
=> Fix test for update of position tools

docs/mkdocs.yml
=> Fix notebook name

.github/workflows/test-package-build.yml, CHANGELOG.md, CITATION.cff
New release to incorporate latest changes.
=> Bump version number

CHANGELOG.md, src/spyglass/common/common_nwbfile.py
Resolves #894 
- within `AnalysisNwbfile.create()` 
- save spyglass version in `nwbf.source_script`
=> Add spyglass version to created analysis nwb files

src/spyglass/common/common_nwbfile.py
Fix to the implementation of #897 to overwrite pre-existing source script (if present) with spyglass version. 
ex)
the [trodes_to_nwb source script](https://github.com/LorenFrankLab/trodes_to_nwb/blob/f2113926606fc3da9bc68ce848ed180cb063ca97/src/trodes_to_nwb/convert_yaml.py#L96) from the original nwb file should be overwritten by the spyglass version in genertated analysis_nwb files
=> Quickfix: Change existing source script to spyglass version

CHANGELOG.md, src/spyglass/decoding/v1/clusterless.py, src/spyglass/spikesorting/spikesorting_merge.py
=> Hot fixes for clusterless `get_ahead_behind_distance` and `get_spike_times`

src/spyglass/utils/dj_helper_fn.py
fixes #912 
- Fixes minor bugs in `fetch_nwb`
=> Quickfix for fetch_nwb

README.md
Nature methods has a couple of requirements for the readme such as adding system requirements and typical installation time.
=> Add system requirements and typical installation time

src/spyglass/spikesorting/v0/spikesorting_curation.py
Fixes #959 
-Don't alter the make key with the analysis file name until after fetching waveform data
=> QuickFix: Bug in curation v0 make

CHANGELOG.md, src/spyglass/position/v1/position_dlc_centroid.py, src/spyglass/position/v1/position_dlc_orient.py, src/spyglass/position/v1/position_dlc_pose_estimation.py, src/spyglass/position/v1/position_dlc_position.py, src/spyglass/position/v1/position_dlc_selection.py
Reverts LorenFrankLab/spyglass#970
=> Revert "Allow dlc pipeline to run without prior position tracking"

CHANGELOG.md, src/spyglass/common/common_behav.py, src/spyglass/position/v1/position_dlc_centroid.py, src/spyglass/position/v1/position_dlc_orient.py, src/spyglass/position/v1/position_dlc_pose_estimation.py, src/spyglass/position/v1/position_dlc_position.py, src/spyglass/position/v1/position_dlc_selection.py
Fixes #950 
- sources meters to pixels conversion from the camera device in the nwb
- make metadata from pre-existing spatial series optional
Fixes #961 
- avoid altering `analysis_file_name` in make functions before fetching needed data
=> Allow dlc pipeline to run without prior position tracking

.github/pull_request_template.md, CHANGELOG.md, docs/mkdocs.yml, docs/src/misc/common_errs.md, docs/src/misc/index.md
- Adds list of common errors users might encounter
- Sorts 'misc' docs alphabetically
=> Add Common Errors doc

CHANGELOG.md, src/spyglass/spikesorting/v0/figurl_views/SpikeSortingRecordingView.py, src/spyglass/spikesorting/v0/figurl_views/SpikeSortingView.py
Resolves #1013
- Removes dependency on `kachery_client` and updates calls to `kachery_cloud` in `spikesorting.v0.figurl_views`
=> Remove kachery_client dependency

README.md
Badge is pointing to the wrong tests
=> Fix test badge

CHANGELOG.md, src/spyglass/position/v1/dlc_utils_makevid.py
Fix inspired by debugging #1146
=> DLC `make_video` minor fixes

CHANGELOG.md, src/spyglass/utils/dj_merge_tables.py, src/spyglass/utils/mixins/export.py, tests/common/conftest.py, tests/common/test_position.py, tests/common/test_usage.py, tests/utils/conftest.py
This PR updates tests based on #1048 
- changing inheritance order requires initialization where previously not neede
- adding another arg to `merge_fetch` prevented calling attrs as positional arguments
=> Fix failing tests

.pre-commit-config.yaml, CHANGELOG.md, maintenance_scripts/README.md, maintenance_scripts/check_disk_space.sh, maintenance_scripts/cleanup.py, maintenance_scripts/example.env, maintenance_scripts/run_jobs.sh, src/spyglass/spikesorting/v0/spikesorting_recording.py, src/spyglass/spikesorting/v0/spikesorting_sorting.py
- Update cron job to include...
- running `chmod` on new files
- cleanup of spikesorting v0 dir
- Update cleanup of `v0.SpikeSorting` to remove untracked files 
Marked as draft pending communal review of would-be-deleted files
Closes #183
=> Revise cleanup scripts 

CHANGELOG.md, src/spyglass/common/common_sensors.py
Add helpful method to SensorData to acess data.
Allows for filtering by interval for efficient loading.
=> Add fetch1_dataframe to sensor data

CHANGELOG.md, docs/src/Features/Export.md, pyproject.toml, src/spyglass/common/common_behav.py, src/spyglass/common/common_device.py, src/spyglass/common/common_ephys.py, src/spyglass/common/common_nwbfile.py, src/spyglass/common/common_region.py, src/spyglass/common/common_task.py, src/spyglass/common/common_usage.py, src/spyglass/data_import/__init__.py, src/spyglass/decoding/v0/sorted_spikes.py, src/spyglass/lfp/analysis/v1/lfp_band.py, src/spyglass/position/v1/position_dlc_cohort.py, src/spyglass/position/v1/position_dlc_model.py, src/spyglass/position/v1/position_dlc_position.py, src/spyglass/position/v1/position_dlc_project.py, src/spyglass/position/v1/position_trodes_position.py, src/spyglass/sharing/sharing_kachery.py, src/spyglass/spikesorting/spikesorting_merge.py, src/spyglass/spikesorting/v0/spikesorting_recording.py, src/spyglass/spikesorting/v0/spikesorting_sorting.py, src/spyglass/spikesorting/v1/metric_curation.py, src/spyglass/spikesorting/v1/recording.py, src/spyglass/utils/dj_helper_fn.py, src/spyglass/utils/dj_mixin.py, src/spyglass/utils/nwb_helper_fn.py, tests/conftest.py, tests/linearization/test_lin.py, tests/position/test_trodes.py
We're in the habit of noting an inline 'TODO' either for the present PR or some minor issue, rather than opening up an issue. These are harder to track. In this PR, I address a handful by ... 
- delete outdated items previously addressed
- doing some refactoring to address the TODO
- migrating to an issue
=> Cut down TODOs, part 1: 57 -> 43

.github/workflows/test-conda.yml, CHANGELOG.md, pyproject.toml, src/spyglass/position/v1/position_dlc_position.py, tests/README.md, tests/common/test_behav.py
This PR...
1. Fixes some failing position tests from #1304 specific to the `TEARDOWN` case 
2. Adds a badge as a reminder of coverage using Codecov. This also adds a nice GUI for the dev team to reference 
<details><summary>GUI Example</summary>
</details>
=> Add badge to tests README

CHANGELOG.md, notebooks/00_Setup.ipynb, notebooks/py_scripts/00_Setup.py
At a recent meeting with new users, one person requested an edit regarding the suggestion to stay up to date with git commits. This PR adds notes to the setup instructions
=> Update install instructions

.github/codecov.yml, .github/pull_request_template.md, CHANGELOG.md
Prevent failing test via patch coverage diff
=> Disable codecov patch check

CHANGELOG.md, pyproject.toml
=> Update pynwb pin

docs/mkdocs.yml, docs/src/api/ingestion_mapping_generate.py, src/spyglass/common/common_device.py, src/spyglass/common/common_ephys.py, src/spyglass/common/common_lab.py, src/spyglass/common/common_nwbfile.py, src/spyglass/common/common_session.py, src/spyglass/common/populate_all_common.py, src/spyglass/data_import/insert_sessions.py, src/spyglass/utils/dj_mixin.py
- Auto-gen mapping doc on docs build
- Refactor
=> WIP: Standard import 

.gitignore, CHANGELOG.md, src/spyglass/position/v1/dlc_utils_makevid.py, src/spyglass/position/v1/position_dlc_selection.py, tests/position/v1/test_dlc_position.py
This PR edits...
- `gitignore` to ignore the yaml env dump created during tests
- `makevid` to add a number of intermediate checks to the process, raising more informative errors
- `dlc_selection` to address #1417
=> Debug VideoMaker - fix failing test
